import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, FlatList, Image, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useInfiniteQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { api } from '../../../src/api/client';
import { ScreenMessage } from '../../../src/components/ScreenMessage';
import { getAuthToken } from '../../../src/stores/auth';
import { colors, radius, spacing } from '../../../src/theme';
import type { Video } from '../../../src/types/api';
import { absoluteMediaUrl } from '../../../src/utils/url';

type Filter = 'all' | 'published' | 'draft';
type Page = { data: Video[]; meta: { current_page: number; last_page: number } };
const filters: { key: Filter; label: string }[] = [{ key: 'all', label: 'All' }, { key: 'published', label: 'Published' }, { key: 'draft', label: 'Drafts' }];

export default function MyPostsScreen() {
  const [filter, setFilter] = useState<Filter>('all');
  const [token, setToken] = useState<string>();
  const queryClient = useQueryClient();
  useEffect(() => { getAuthToken().then(value => setToken(value ?? undefined)); }, []);
  const posts = useInfiniteQuery({ queryKey: ['videos', 'mine', filter], initialPageParam: 1, queryFn: async ({ pageParam }) => (await api.get('/videos/mine', { params: { page: pageParam, ...(filter === 'all' ? {} : { status: filter }) } })).data as Page, getNextPageParam: page => page.meta.current_page < page.meta.last_page ? page.meta.current_page + 1 : undefined });
  const remove = useMutation({ mutationFn: (id: string) => api.delete('/videos/' + id), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['videos', 'mine'] }); queryClient.invalidateQueries({ queryKey: ['feed'] }); }, onError: (error: any) => Alert.alert('Post not deleted', error?.response?.data?.message || 'Please try again.') });
  const publish = useMutation({ mutationFn: (id: string) => api.post('/videos/' + id + '/publish'), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['videos', 'mine'] }); queryClient.invalidateQueries({ queryKey: ['feed'] }); }, onError: (error: any) => Alert.alert('Draft not published', error?.response?.data?.message || 'Please try again.') });
  const items = posts.data?.pages.flatMap(page => page.data) ?? [];
  const confirmDelete = (post: Video) => Alert.alert('Delete this post?', 'This permanently removes the post and its engagement history.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: () => remove.mutate(post.id) }]);

  return <SafeAreaView edges={['top']} style={styles.safe}><View style={styles.header}><Pressable accessibilityLabel="Go back" hitSlop={12} onPress={() => router.back()}><Ionicons name="chevron-back" size={26} color="#fff" /></Pressable><Text style={styles.headerTitle}>My posts</Text><Pressable accessibilityLabel="Create post" hitSlop={10} onPress={() => router.push('/upload')}><Ionicons name="add-circle-outline" size={25} color="#fff" /></Pressable></View><View style={styles.filters}>{filters.map(item => <Pressable accessibilityRole="tab" accessibilityState={{ selected: filter === item.key }} key={item.key} onPress={() => setFilter(item.key)} style={[styles.filter, filter === item.key && styles.filterActive]}><Text style={[styles.filterText, filter === item.key && styles.filterTextActive]}>{item.label}</Text></Pressable>)}</View><FlatList data={items} keyExtractor={item => item.id} contentContainerStyle={items.length ? styles.list : styles.emptyList} renderItem={({ item }) => <PostRow post={item} token={token} busy={remove.isPending || publish.isPending} onEdit={() => router.push({ pathname: '/post/[id]/edit', params: { id: item.id } })} onPublish={() => publish.mutate(item.id)} onDelete={() => confirmDelete(item)} />} ItemSeparatorComponent={() => <View style={{ height: 11 }} />} refreshing={posts.isRefetching && !posts.isFetchingNextPage} onRefresh={() => posts.refetch()} onEndReached={() => { if (posts.hasNextPage && !posts.isFetchingNextPage) posts.fetchNextPage(); }} onEndReachedThreshold={.4} ListFooterComponent={posts.isFetchingNextPage ? <ActivityIndicator style={styles.footer} color={colors.blue} /> : null} ListEmptyComponent={posts.isLoading ? <ActivityIndicator style={styles.loader} color={colors.blue} /> : posts.isError ? <ScreenMessage icon="cloud-offline-outline" title="Posts unavailable" message="Check your connection and try again." /> : <ScreenMessage icon={filter === 'draft' ? 'document-outline' : 'images-outline'} title={filter === 'draft' ? 'No drafts' : 'No posts yet'} message={filter === 'draft' ? 'Posts saved as drafts will appear here.' : 'Share your first sporting moment.'} />} /></SafeAreaView>;
}

function PostRow({ post, token, busy, onEdit, onPublish, onDelete }: { post: Video; token?: string; busy: boolean; onEdit: () => void; onPublish: () => void; onDelete: () => void }) { const image = post.images?.find(item => item.is_cover) ?? post.images?.[0]; return <View style={styles.card}><View style={styles.preview}>{image ? <Image source={{ uri: absoluteMediaUrl(image.download_url), headers: token ? { Authorization: 'Bearer ' + token } : undefined }} style={styles.image} /> : <View style={styles.videoPlaceholder}><Ionicons name="play-circle" size={38} color="#79A3FF" /><Text style={styles.videoText}>Video</Text></View>}<View style={[styles.status, post.status === 'draft' && styles.draft]}><Text style={styles.statusText}>{post.status === 'draft' ? 'DRAFT' : post.visibility?.toUpperCase() || 'PUBLISHED'}</Text></View></View><View style={styles.cardBody}><Text numberOfLines={2} style={styles.caption}>{post.caption || 'Untitled post'}</Text><Text style={styles.meta}>{post.counts.views} views · {post.counts.likes} likes · {post.counts.comments} comments</Text><View style={styles.actions}>{post.status === 'draft' ? <Pressable disabled={busy} onPress={onPublish} style={[styles.action, styles.publish]}><Ionicons name="paper-plane-outline" size={16} color="#fff" /><Text style={styles.actionText}>Publish</Text></Pressable> : null}<Pressable disabled={busy} onPress={onEdit} style={styles.action}><Ionicons name="create-outline" size={16} color="#fff" /><Text style={styles.actionText}>Edit</Text></Pressable><Pressable disabled={busy} onPress={onDelete} style={styles.delete}><Ionicons name="trash-outline" size={18} color={colors.danger} /></Pressable></View></View></View>; }

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.navy }, header: { height: 56, paddingHorizontal: spacing.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.line }, headerTitle: { color: '#fff', fontSize: 18, fontWeight: '900' }, filters: { margin: spacing.md, marginBottom: 4, height: 42, padding: 3, flexDirection: 'row', borderRadius: 12, backgroundColor: colors.surface }, filter: { flex: 1, alignItems: 'center', justifyContent: 'center', borderRadius: 9 }, filterActive: { backgroundColor: colors.blue }, filterText: { color: colors.muted, fontSize: 12, fontWeight: '800' }, filterTextActive: { color: '#fff' }, list: { padding: spacing.md, paddingBottom: 40 }, emptyList: { flexGrow: 1 }, loader: { marginTop: 100 }, footer: { margin: 20 }, card: { overflow: 'hidden', flexDirection: 'row', minHeight: 142, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface }, preview: { width: 126, backgroundColor: '#07101B' }, image: { width: '100%', height: '100%' }, videoPlaceholder: { flex: 1, alignItems: 'center', justifyContent: 'center' }, videoText: { color: colors.muted, fontSize: 10, fontWeight: '800' }, status: { position: 'absolute', left: 7, top: 7, paddingHorizontal: 7, paddingVertical: 4, borderRadius: 6, backgroundColor: colors.blue }, draft: { backgroundColor: colors.orange }, statusText: { color: '#fff', fontSize: 8, fontWeight: '900' }, cardBody: { flex: 1, padding: 13 }, caption: { color: '#fff', fontSize: 14, lineHeight: 19, fontWeight: '800' }, meta: { color: colors.muted, fontSize: 10, marginTop: 6 }, actions: { flex: 1, flexDirection: 'row', alignItems: 'flex-end', gap: 7, marginTop: 10 }, action: { minHeight: 34, paddingHorizontal: 11, flexDirection: 'row', alignItems: 'center', gap: 5, borderRadius: 9, backgroundColor: colors.surfaceRaised }, publish: { backgroundColor: colors.blue }, actionText: { color: '#fff', fontSize: 10, fontWeight: '800' }, delete: { width: 34, height: 34, marginLeft: 'auto', alignItems: 'center', justifyContent: 'center', borderRadius: 9, backgroundColor: 'rgba(255,107,129,.08)' } });
