import { useState } from 'react';
import { ActivityIndicator, Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '../../../src/api/client';
import { PrimaryButton } from '../../../src/components/PrimaryButton';
import { ScreenMessage } from '../../../src/components/ScreenMessage';
import { colors, radius, spacing } from '../../../src/theme';
import type { AthleteAchievement, AthleteCareer, AthleteStatistic, CareerEntry } from '../../../src/types/api';

type Section = 'history' | 'achievements' | 'statistics';
const tabs: { key: Section; label: string }[] = [{ key: 'history', label: 'History' }, { key: 'achievements', label: 'Awards' }, { key: 'statistics', label: 'Stats' }];
const emptyCareer: AthleteCareer = { history: [], achievements: [], statistics: [] };

export default function CareerScreen() {
  const [section, setSection] = useState<Section>('history');
  const [adding, setAdding] = useState(false);
  const queryClient = useQueryClient();
  const career = useQuery({ queryKey: ['profile', 'career'], queryFn: async () => (await api.get('/profile/career')).data.data as AthleteCareer });
  const remove = useMutation({ mutationFn: ({ section, id }: { section: Section; id: number }) => api.delete('/profile/career/' + section + '/' + id), onSuccess: () => refresh(queryClient), onError: (error: any) => Alert.alert('Record not removed', error?.response?.data?.message || 'Please try again.') });
  const confirmRemove = (id: number) => Alert.alert('Remove this record?', 'This action cannot be undone.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Remove', style: 'destructive', onPress: () => remove.mutate({ section, id }) }]);
  const data = career.data ?? emptyCareer;

  return <SafeAreaView edges={['top']} style={styles.safe}><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={styles.header}><Pressable accessibilityLabel="Go back" hitSlop={12} onPress={() => router.back()}><Ionicons name="chevron-back" size={26} color="#fff" /></Pressable><Text style={styles.headerTitle}>Career portfolio</Text><Pressable accessibilityLabel="Add career record" hitSlop={10} onPress={() => setAdding(value => !value)}><Ionicons name={adding ? 'close-circle-outline' : 'add-circle-outline'} size={25} color="#fff" /></Pressable></View><View style={styles.tabs}>{tabs.map(tab => <Pressable accessibilityRole="tab" accessibilityState={{ selected: section === tab.key }} key={tab.key} onPress={() => { setSection(tab.key); setAdding(false); }} style={[styles.tab, section === tab.key && styles.tabActive]}><Text style={[styles.tabText, section === tab.key && styles.tabTextActive]}>{tab.label}</Text></Pressable>)}</View><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">{adding ? <AddForm section={section} onDone={() => { setAdding(false); refresh(queryClient); }} /> : null}{career.isLoading ? <ActivityIndicator style={styles.loader} color={colors.blue} /> : career.isError ? <ScreenMessage icon="cloud-offline-outline" title="Portfolio unavailable" message="Check your connection and try again." /> : <Records section={section} career={data} onRemove={confirmRemove} />}</ScrollView></KeyboardAvoidingView></SafeAreaView>;
}

function Records({ section, career, onRemove }: { section: Section; career: AthleteCareer; onRemove: (id: number) => void }) {
  const items = career[section];
  if (!items.length) return <ScreenMessage icon={section === 'history' ? 'briefcase-outline' : section === 'achievements' ? 'trophy-outline' : 'stats-chart-outline'} title={`No ${section === 'achievements' ? 'awards' : section} yet`} message="Use the add button to build your athlete portfolio." />;
  return <View style={styles.records}>{section === 'history' ? (items as CareerEntry[]).map(item => <Record key={item.id} title={item.team_name} subtitle={[item.role, item.level].filter(Boolean).join(' · ')} meta={item.is_current ? `${date(item.started_on)} – Present` : `${date(item.started_on)} – ${date(item.ended_on)}`} description={item.description} onRemove={() => onRemove(item.id)} />) : section === 'achievements' ? (items as AthleteAchievement[]).map(item => <Record key={item.id} title={item.title} subtitle={item.issuer ?? ''} meta={date(item.achieved_on)} description={item.description} onRemove={() => onRemove(item.id)} />) : (items as AthleteStatistic[]).map(item => <Record key={item.id} title={`${item.value}${item.unit ? ' ' + item.unit : ''}`} subtitle={item.name} meta={[item.season, item.competition].filter(Boolean).join(' · ')} onRemove={() => onRemove(item.id)} />)}</View>;
}
function Record({ title, subtitle, meta, description, onRemove }: { title: string; subtitle?: string; meta?: string; description?: string | null; onRemove: () => void }) { return <View style={styles.record}><View style={styles.recordTop}><View style={styles.recordCopy}><Text style={styles.recordTitle}>{title}</Text>{subtitle ? <Text style={styles.recordSubtitle}>{subtitle}</Text> : null}</View><Pressable accessibilityLabel="Remove record" hitSlop={10} onPress={onRemove}><Ionicons name="trash-outline" size={19} color={colors.danger} /></Pressable></View>{meta ? <Text style={styles.recordMeta}>{meta}</Text> : null}{description ? <Text style={styles.description}>{description}</Text> : null}</View>; }

function AddForm({ section, onDone }: { section: Section; onDone: () => void }) {
  const [history, setHistory] = useState({ team_name: '', role: '', level: '', started_on: '', ended_on: '', is_current: false, description: '' });
  const [award, setAward] = useState({ title: '', issuer: '', achieved_on: '', description: '' });
  const [stat, setStat] = useState({ season: '', competition: '', name: '', value: '', unit: '' });
  const form = section === 'history' ? history : section === 'achievements' ? award : stat;
  const mutation = useMutation({ mutationFn: () => api.post('/profile/career/' + section, section === 'history' ? history : section === 'achievements' ? award : { ...stat, value: Number(stat.value) }), onSuccess: onDone, onError: (error: any) => Alert.alert('Record not added', Object.values(error?.response?.data?.errors || {}).flat()?.[0] as string || error?.response?.data?.message || 'Check the information and try again.') });
  const ready = section === 'history' ? Boolean(history.team_name) : section === 'achievements' ? Boolean(award.title) : Boolean(stat.season && stat.name && stat.value);
  const field = (key: string, value: string) => section === 'history' ? setHistory(current => ({ ...current, [key]: value })) : section === 'achievements' ? setAward(current => ({ ...current, [key]: value })) : setStat(current => ({ ...current, [key]: value }));
  return <View style={styles.form}><Text style={styles.formTitle}>Add {section === 'history' ? 'career history' : section === 'achievements' ? 'achievement' : 'statistic'}</Text>{section === 'history' ? <><Field label="Team or organisation" value={history.team_name} onChangeText={value => field('team_name', value)} /><Field label="Role or position" value={history.role} onChangeText={value => field('role', value)} /><Field label="Level" value={history.level} onChangeText={value => field('level', value)} /><View style={styles.columns}><Field label="Started (YYYY-MM-DD)" value={history.started_on} onChangeText={value => field('started_on', value)} style={styles.column} /><Field label="Ended (YYYY-MM-DD)" value={history.ended_on} onChangeText={value => field('ended_on', value)} style={styles.column} editable={!history.is_current} /></View><View style={styles.current}><Text style={styles.currentText}>I currently play here</Text><Switch value={history.is_current} onValueChange={is_current => setHistory(current => ({ ...current, is_current, ended_on: is_current ? '' : current.ended_on }))} trackColor={{ false: colors.surfaceRaised, true: colors.blue }} /></View><Field label="Description" value={history.description} onChangeText={value => field('description', value)} multiline /></> : section === 'achievements' ? <><Field label="Achievement title" value={award.title} onChangeText={value => field('title', value)} /><Field label="Issuer or competition" value={award.issuer} onChangeText={value => field('issuer', value)} /><Field label="Date achieved (YYYY-MM-DD)" value={award.achieved_on} onChangeText={value => field('achieved_on', value)} /><Field label="Description" value={award.description} onChangeText={value => field('description', value)} multiline /></> : <><Field label="Season" value={stat.season} onChangeText={value => field('season', value)} placeholder="2025/26" /><Field label="Competition" value={stat.competition} onChangeText={value => field('competition', value)} /><Field label="Statistic name" value={stat.name} onChangeText={value => field('name', value)} placeholder="Goals, assists, personal best…" /><View style={styles.columns}><Field label="Value" value={stat.value} onChangeText={value => field('value', value.replace(/[^\d.-]/g, ''))} keyboardType="decimal-pad" style={styles.column} /><Field label="Unit" value={stat.unit} onChangeText={value => field('unit', value)} placeholder="goals, sec…" style={styles.column} /></View></>}<PrimaryButton label="Add record" loading={mutation.isPending} disabled={!ready} onPress={() => mutation.mutate()} style={{ marginTop: 18 }} /></View>;
}

function Field({ label, style, multiline, ...props }: { label: string; style?: any; multiline?: boolean } & React.ComponentProps<typeof TextInput>) { return <View style={style}><Text style={styles.label}>{label}</Text><TextInput {...props} multiline={multiline} placeholderTextColor="#71849B" style={[styles.input, multiline && styles.textarea]} textAlignVertical={multiline ? 'top' : 'center'} /></View>; }
function date(value?: string | null) { return value ? new Date(value).toLocaleDateString() : 'Date not set'; }
function refresh(client: ReturnType<typeof useQueryClient>) { client.invalidateQueries({ queryKey: ['profile', 'career'] }); client.invalidateQueries({ queryKey: ['profile'] }); }

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.navy }, flex: { flex: 1 }, header: { height: 56, paddingHorizontal: spacing.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.line }, headerTitle: { color: '#fff', fontSize: 18, fontWeight: '900' }, tabs: { height: 44, margin: spacing.md, marginBottom: 0, padding: 3, flexDirection: 'row', borderRadius: 12, backgroundColor: colors.surface }, tab: { flex: 1, alignItems: 'center', justifyContent: 'center', borderRadius: 9 }, tabActive: { backgroundColor: colors.blue }, tabText: { color: colors.muted, fontSize: 12, fontWeight: '800' }, tabTextActive: { color: '#fff' }, content: { flexGrow: 1, padding: spacing.md, paddingBottom: 45 }, loader: { marginTop: 100 }, records: { gap: 10 }, record: { padding: spacing.md, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface }, recordTop: { flexDirection: 'row', gap: 10 }, recordCopy: { flex: 1 }, recordTitle: { color: '#fff', fontSize: 17, fontWeight: '900' }, recordSubtitle: { color: '#79A3FF', fontSize: 12, fontWeight: '800', marginTop: 3 }, recordMeta: { color: colors.muted, fontSize: 11, marginTop: 9 }, description: { color: '#D8E2EE', fontSize: 12, lineHeight: 18, marginTop: 10 }, form: { padding: spacing.md, marginBottom: 16, borderRadius: radius.lg, borderWidth: 1, borderColor: 'rgba(71,111,234,.45)', backgroundColor: colors.surface }, formTitle: { color: '#fff', fontSize: 18, fontWeight: '900', marginBottom: 4 }, label: { color: '#DCE7F5', fontSize: 11, fontWeight: '800', marginTop: 14, marginBottom: 6 }, input: { minHeight: 48, paddingHorizontal: 13, borderRadius: radius.md, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.navyLight, color: '#fff' }, textarea: { height: 90, paddingTop: 12 }, columns: { flexDirection: 'row', gap: 9 }, column: { flex: 1 }, current: { minHeight: 52, marginTop: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, currentText: { color: '#fff', fontSize: 12, fontWeight: '800' } });
