import { useState } from 'react';
import { ActivityIndicator, Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '../../../../src/api/client';
import { ScreenMessage } from '../../../../src/components/ScreenMessage';
import { colors, radius, spacing } from '../../../../src/theme';
import type { OpportunityApplication, PaginatedResponse } from '../../../../src/types/api';

const statuses = ['reviewing', 'shortlisted', 'accepted', 'rejected'] as const;
export default function ApplicantsScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const client = useQueryClient();
  const [selected, setSelected] = useState<OpportunityApplication>();
  const [notes, setNotes] = useState('');
  const applicants = useQuery({ queryKey: ['opportunity', id, 'applicants'], queryFn: async () => (await api.get<PaginatedResponse<OpportunityApplication>>(`/opportunities/${id}/applications`)).data.data, enabled: Boolean(id) });
  const review = useMutation({ mutationFn: (status: typeof statuses[number]) => api.patch('/applications/' + selected!.id, { status, reviewer_notes: notes.trim() || undefined }), onSuccess: async () => { setSelected(undefined); setNotes(''); await Promise.all([client.invalidateQueries({ queryKey: ['opportunity', id, 'applicants'] }), client.invalidateQueries({ queryKey: ['opportunities', 'mine'] })]); }, onError: (error: any) => Alert.alert('Status not updated', error?.response?.data?.message || 'Please try again.') });
  const items = applicants.data ?? [];
  return <SafeAreaView edges={['top']} style={styles.safe}><View style={styles.header}><Pressable accessibilityLabel="Go back" onPress={() => router.back()}><Ionicons name="chevron-back" size={26} color="#fff" /></Pressable><Text style={styles.headerTitle}>Applicants</Text><View style={{ width: 26 }} /></View><FlatList data={items} keyExtractor={item => item.id} contentContainerStyle={items.length ? styles.list : styles.empty} refreshing={applicants.isRefetching} onRefresh={() => applicants.refetch()} ItemSeparatorComponent={() => <View style={{ height: 10 }} />} ListEmptyComponent={applicants.isLoading ? <ActivityIndicator style={styles.loader} color={colors.blue} /> : <ScreenMessage icon="people-outline" title="No applicants yet" message="New applications will appear here." />} renderItem={({ item }) => <View style={styles.card}><View style={styles.person}><View style={styles.avatar}><Text style={styles.initial}>{item.applicant.name.charAt(0)}</Text></View><View style={styles.personCopy}><Pressable disabled={!item.applicant.slug} onPress={() => item.applicant.slug && router.push(`/profile/${item.applicant.slug}` as never)}><Text style={styles.name}>{item.applicant.name}</Text></Pressable><Text style={styles.date}>Applied {new Date(item.created_at).toLocaleDateString()}</Text></View><Status value={item.status} /></View>{item.cover_letter ? <Text numberOfLines={selected?.id === item.id ? undefined : 3} style={styles.letter}>{item.cover_letter}</Text> : null}{selected?.id === item.id ? <View style={styles.review}><Text style={styles.reviewLabel}>Private review notes</Text><TextInput value={notes} onChangeText={setNotes} multiline maxLength={5000} placeholder="Add instructions or reasons…" placeholderTextColor="#71849B" style={styles.notes} textAlignVertical="top" /><View style={styles.statuses}>{statuses.map(status => <Pressable disabled={review.isPending} key={status} onPress={() => review.mutate(status)} style={[styles.statusButton, status === 'accepted' && styles.accept, status === 'rejected' && styles.reject]}><Text style={styles.statusButtonText}>{status}</Text></Pressable>)}</View><Pressable onPress={() => setSelected(undefined)}><Text style={styles.cancel}>Cancel review</Text></Pressable></View> : <Pressable onPress={() => { setSelected(item); setNotes(item.reviewer_notes ?? ''); }} style={styles.reviewButton}><Ionicons name="clipboard-outline" size={17} color="#fff" /><Text style={styles.reviewButtonText}>Review application</Text></Pressable>}</View>} /></SafeAreaView>;
}
function Status({ value }: { value: string }) { return <View style={[styles.status, value === 'accepted' && styles.accept, value === 'rejected' && styles.reject, value === 'shortlisted' && styles.shortlist]}><Text style={styles.statusText}>{value}</Text></View>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.navy }, header: { height: 56, paddingHorizontal: spacing.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.line }, headerTitle: { color: '#fff', fontSize: 17, fontWeight: '900' }, list: { padding: spacing.md, paddingBottom: 40 }, empty: { flexGrow: 1 }, loader: { marginTop: 100 }, card: { padding: spacing.md, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface }, person: { flexDirection: 'row', alignItems: 'center', gap: 10 }, avatar: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.blue }, initial: { color: '#fff', fontSize: 17, fontWeight: '900' }, personCopy: { flex: 1 }, name: { color: '#fff', fontSize: 15, fontWeight: '900' }, date: { color: colors.muted, fontSize: 10, marginTop: 3 }, status: { paddingHorizontal: 8, paddingVertical: 5, borderRadius: 7, backgroundColor: colors.surfaceRaised }, statusText: { color: '#fff', fontSize: 8, fontWeight: '900', textTransform: 'uppercase' }, shortlist: { backgroundColor: colors.orange }, accept: { backgroundColor: colors.green }, reject: { backgroundColor: colors.danger }, letter: { color: '#D6E1ED', fontSize: 12, lineHeight: 18, marginTop: 13 }, reviewButton: { alignSelf: 'flex-start', minHeight: 38, marginTop: 14, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 6, borderRadius: 9, backgroundColor: colors.blue }, reviewButtonText: { color: '#fff', fontSize: 11, fontWeight: '800' }, review: { marginTop: 16, paddingTop: 14, borderTopWidth: 1, borderTopColor: colors.line }, reviewLabel: { color: '#fff', fontSize: 11, fontWeight: '800' }, notes: { height: 100, marginTop: 7, padding: 12, borderRadius: radius.md, backgroundColor: colors.navyLight, color: '#fff' }, statuses: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 10 }, statusButton: { paddingHorizontal: 10, paddingVertical: 9, borderRadius: 8, backgroundColor: colors.blue }, statusButtonText: { color: '#fff', fontSize: 9, fontWeight: '900', textTransform: 'capitalize' }, cancel: { color: colors.muted, fontSize: 11, fontWeight: '800', textAlign: 'center', marginTop: 13 } });
