import { Alert, FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '../../src/api/client';
import { ScreenMessage } from '../../src/components/ScreenMessage';
import { colors, radius, spacing } from '../../src/theme';
import type { OpportunityApplication, PaginatedResponse } from '../../src/types/api';

export default function MyApplicationsScreen() {
  const client = useQueryClient();
  const applications = useQuery({ queryKey: ['applications', 'mine'], queryFn: async () => (await api.get<PaginatedResponse<OpportunityApplication>>('/applications/mine')).data.data });
  const withdraw = useMutation({ mutationFn: (id: string) => api.post('/applications/' + id + '/withdraw'), onSuccess: () => { client.invalidateQueries({ queryKey: ['applications', 'mine'] }); client.invalidateQueries({ queryKey: ['opportunities'] }); }, onError: (error: any) => Alert.alert('Application not withdrawn', error?.response?.data?.message || 'Please try again.') });
  const confirm = (id: string) => Alert.alert('Withdraw application?', 'The organisation will see that you withdrew. This cannot be reversed.', [{ text: 'Keep application', style: 'cancel' }, { text: 'Withdraw', style: 'destructive', onPress: () => withdraw.mutate(id) }]);
  const items = applications.data ?? [];
  return <SafeAreaView edges={['top']} style={styles.safe}><View style={styles.header}><Pressable accessibilityLabel="Go back" onPress={() => router.back()}><Ionicons name="chevron-back" size={26} color="#fff" /></Pressable><Text style={styles.headerTitle}>My applications</Text><View style={{ width: 26 }} /></View><FlatList data={items} keyExtractor={item => item.id} contentContainerStyle={items.length ? styles.list : styles.empty} refreshing={applications.isRefetching} onRefresh={() => applications.refetch()} ItemSeparatorComponent={() => <View style={{ height: 10 }} />} ListEmptyComponent={<ScreenMessage icon="document-text-outline" title="No applications yet" message="Opportunities you apply for will appear here with their latest status." />} renderItem={({ item }) => <Pressable onPress={() => router.push(`/opportunity/${item.opportunity.id}` as never)} style={styles.card}><View style={styles.top}><View style={styles.copy}><Text style={styles.title}>{item.opportunity.title}</Text><Text style={styles.poster}>{item.opportunity.poster.name}</Text></View><Status value={item.status} /></View><View style={styles.timeline}>{item.timeline.map((step, index) => <View key={`${step.status}-${index}`} style={styles.step}><View style={styles.dot} /><View style={styles.stepCopy}><Text style={styles.stepTitle}>{step.status}</Text><Text style={styles.stepDate}>{new Date(step.created_at).toLocaleString()}</Text>{step.notes ? <Text style={styles.notes}>{step.notes}</Text> : null}</View></View>)}</View>{['submitted', 'reviewing', 'shortlisted'].includes(item.status) ? <Pressable disabled={withdraw.isPending} onPress={() => confirm(item.id)} style={styles.withdraw}><Text style={styles.withdrawText}>Withdraw application</Text></Pressable> : null}</Pressable>} /></SafeAreaView>;
}
function Status({ value }: { value: string }) { return <View style={[styles.status, value === 'accepted' && styles.accept, value === 'rejected' && styles.reject, value === 'shortlisted' && styles.shortlist]}><Text style={styles.statusText}>{value}</Text></View>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.navy }, header: { height: 56, paddingHorizontal: spacing.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.line }, headerTitle: { color: '#fff', fontSize: 17, fontWeight: '900' }, list: { padding: spacing.md, paddingBottom: 40 }, empty: { flexGrow: 1 }, card: { padding: spacing.md, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface }, top: { flexDirection: 'row', gap: 10 }, copy: { flex: 1 }, title: { color: '#fff', fontSize: 17, fontWeight: '900' }, poster: { color: '#79A3FF', fontSize: 11, fontWeight: '800', marginTop: 4 }, status: { alignSelf: 'flex-start', paddingHorizontal: 8, paddingVertical: 5, borderRadius: 7, backgroundColor: colors.blue }, statusText: { color: '#fff', fontSize: 8, fontWeight: '900', textTransform: 'uppercase' }, shortlist: { backgroundColor: colors.orange }, accept: { backgroundColor: colors.green }, reject: { backgroundColor: colors.danger }, timeline: { marginTop: 17, paddingTop: 13, borderTopWidth: 1, borderTopColor: colors.line }, step: { flexDirection: 'row', gap: 10, marginBottom: 13 }, dot: { width: 9, height: 9, marginTop: 4, borderRadius: 5, backgroundColor: colors.blue }, stepCopy: { flex: 1 }, stepTitle: { color: '#fff', fontSize: 11, fontWeight: '900', textTransform: 'capitalize' }, stepDate: { color: colors.muted, fontSize: 9, marginTop: 2 }, notes: { color: '#D6E1ED', fontSize: 11, lineHeight: 16, marginTop: 5 }, withdraw: { alignSelf: 'flex-start', paddingVertical: 8, marginTop: 4 }, withdrawText: { color: colors.danger, fontSize: 11, fontWeight: '800' } });
