<script setup lang="ts">
import { Head,Link } from '@inertiajs/vue3';
import { Bookmark,BriefcaseBusiness,Clock3,Filter,Flame,MapPin,Play,Search,Trash2,UserPlus,Users,X } from '@lucide/vue';
import { computed,onMounted,ref,watch } from 'vue';
import AppShell from '../../Layouts/AppShell.vue';
const query=ref(new URLSearchParams(location.search).get('q')??''),loading=ref(true),payload=ref<any>({data:{athletes:[],videos:[],clubs:[],opportunities:[]},discovery:{}}),history=ref<any[]>([]),saved=ref<any[]>([]),savedProfileIds=ref<number[]>([]),sports=ref<any[]>([]),active=ref('all'),saveName=ref(''),saveOpen=ref(false),filtersOpen=ref(false);const filters=ref<any>({role:'athlete',sport_id:'',position_id:'',min_age:'',max_age:'',gender:'',province:'',city:'',available:false,min_completeness:''});let timer:ReturnType<typeof setTimeout>;
const positions=computed(()=>sports.value.find(s=>String(s.id)===String(filters.value.sport_id))?.positions??[]);const filterCount=computed(()=>Object.entries(filters.value).filter(([key,value])=>key!=='role'&&value!==''&&value!==false).length);
const csrf=()=>(document.querySelector('meta[name="csrf-token"]') as HTMLMetaElement)?.content??'';
const resultCount=computed(()=>Object.values(payload.value.data??{}).reduce((n:number,items:any)=>n+(items?.length??0),0));
const api=async(url:string,options:RequestInit={})=>{const r=await fetch(url,{...options,credentials:'same-origin',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':csrf(),...(options.headers??{})}});const body=r.status===204?{}:await r.json();if(!r.ok)throw new Error(body.message??'Request failed.');return body};
const search=async()=>{loading.value=true;const base=await api('/api/v1/search/all?q='+encodeURIComponent(query.value.trim()));if(filtersOpen.value||filterCount.value){const params=new URLSearchParams({q:query.value.trim(),per_page:'50'});Object.entries(filters.value).forEach(([key,value]:any)=>{if(value!==''&&value!==false)params.set(key,value===true?'1':String(value))});const talent=await api('/api/v1/search/profiles?'+params);base.data.athletes=(talent.data??[]).map((person:any)=>({...person,sport:person.athlete?.sport?.name,city:person.location?.city,saved:savedProfileIds.value.includes(person.id)}));active.value='athletes'}payload.value=base;loading.value=false;if(query.value.trim())loadLibrary()};
const loadLibrary=async()=>{const [h,s,p,sp]=await Promise.all([api('/api/v1/search/history'),api('/api/v1/saved-searches'),api('/api/v1/saved-profiles'),api('/api/v1/sports')]);history.value=h.data??[];saved.value=s.data??[];savedProfileIds.value=(p.data??[]).map((person:any)=>person.id);sports.value=sp.data??[]};
const saveSearch=async()=>{if(!saveName.value.trim())return;await api('/api/v1/saved-searches',{method:'POST',body:JSON.stringify({name:saveName.value.trim(),query:query.value.trim(),filters:filters.value})});saveName.value='';saveOpen.value=false;loadLibrary()};
const removeSaved=async(id:number)=>{await api('/api/v1/saved-searches/'+id,{method:'DELETE'});loadLibrary()};
const clearHistory=async()=>{await api('/api/v1/search/history',{method:'DELETE'});history.value=[]};
const useSearch=(value:string)=>{query.value=value;active.value='all'};
const follow=async(person:any)=>{await api('/api/v1/profiles/'+person.id+'/follow',{method:'POST',body:'{}'});person.following=true};
const saveProfile=async(person:any)=>{const savedNow=person.saved||savedProfileIds.value.includes(person.id);await api('/api/v1/saved-profiles/'+person.id,{method:savedNow?'DELETE':'POST',body:'{}'});person.saved=!savedNow;savedProfileIds.value=person.saved?[...new Set([...savedProfileIds.value,person.id])]:savedProfileIds.value.filter(id=>id!==person.id)};
watch(query,()=>{clearTimeout(timer);timer=setTimeout(search,300)});
onMounted(()=>Promise.all([search(),loadLibrary()]));
</script>
<template><Head title="Discover"/><AppShell><main class="unified-discover"><header><div><h1>Discover SportUniverse</h1><p>Find talent, videos, clubs and opportunities across South Africa.</p></div><form @submit.prevent="search"><Search/><input v-model="query" placeholder="Search anything: names, cities, sports, clubs, titles…"/><button v-if="query" type="button" @click="query=''"><X/></button></form></header>
<div class="discover-tools"><nav><button v-for="tab in ['all','athletes','videos','clubs','opportunities']" :class="{active:active===tab}" @click="active=tab">{{tab}}</button></nav><button @click="filtersOpen=!filtersOpen"><Filter/>Talent filters <b v-if="filterCount">{{filterCount}}</b></button><button v-if="query.trim()||filterCount" @click="saveOpen=true"><Bookmark/>Save search</button></div>
<section v-if="filtersOpen" class="talent-filters"><label>Role<select v-model="filters.role"><option v-for="role in ['athlete','coach','referee','linesman','scout','agent']" :value="role">{{role}}</option></select></label><label>Sport<select v-model="filters.sport_id" @change="filters.position_id='' "><option value="">All sports</option><option v-for="sport in sports" :value="sport.id">{{sport.name}}</option></select></label><label>Position<select v-model="filters.position_id"><option value="">All positions</option><option v-for="position in positions" :value="position.id">{{position.name}}</option></select></label><label>Minimum age<input v-model="filters.min_age" type="number" min="5" max="100"/></label><label>Maximum age<input v-model="filters.max_age" type="number" min="5" max="100"/></label><label>Gender<select v-model="filters.gender"><option value="">Any gender</option><option>female</option><option>male</option><option>non-binary</option></select></label><label>Province<input v-model="filters.province"/></label><label>City<input v-model="filters.city"/></label><label>Minimum completeness<input v-model="filters.min_completeness" type="number" min="0" max="100"/></label><label class="filter-check"><input v-model="filters.available" type="checkbox"/>Available now</label><button @click="search">Apply filters</button></section>
<section v-if="saveOpen" class="save-search-bar"><input v-model="saveName" placeholder="Name this search"/><button @click="saveSearch">Save</button><button @click="saveOpen=false"><X/></button></section>
<p v-if="loading" class="discover-loading">Searching SportUniverse…</p>
<template v-else>
<section v-if="query.trim()" class="search-library"><div v-if="history.length"><header><h2><Clock3/>Recent searches</h2><button @click="clearHistory">Clear</button></header><div><button v-for="item in history.slice(0,8)" @click="useSearch(item.query)">{{item.query}}</button></div></div><div v-if="saved.length"><header><h2><Bookmark/>Saved searches</h2></header><div><button v-for="item in saved" @click="useSearch(item.query)">{{item.name}}<Trash2 @click.stop="removeSaved(item.id)"/></button></div></div></section>
<div class="unified-summary"><strong>{{resultCount}} results</strong><span v-if="query">for “{{query}}”</span></div>
<section v-if="(active==='all'||active==='athletes')&&payload.data.athletes?.length" class="discovery-group"><header><h2><Users/>Talent</h2><button @click="active='athletes'">View all</button></header><div class="account-grid"><article v-for="person in payload.data.athletes"><span><img v-if="person.images?.profile||person.image" :src="person.images?.profile||person.image"/> <template v-else>{{person.name.slice(0,2).toUpperCase()}}</template></span><div><Link :href="'/@'+person.slug">{{person.name}}</Link><small>{{[person.sport,person.city].filter(Boolean).join(' · ')}}</small><p>{{person.bio}}</p></div><button :class="{saved:person.saved||savedProfileIds.includes(person.id)}" aria-label="Save profile" @click="saveProfile(person)"><Bookmark :fill="person.saved||savedProfileIds.includes(person.id)?'currentColor':'none'"/></button><button v-if="!person.following" aria-label="Follow" @click="follow(person)"><UserPlus/></button></article></div></section>
<section v-if="(active==='all'||active==='videos')&&payload.data.videos?.length" class="discovery-group"><header><h2><Play/>Videos</h2><button @click="active='videos'">View all</button></header><div class="discovery-video-grid"><a v-for="video in payload.data.videos" :href="'/feed#'+video.id"><div><img v-if="video.thumbnail" :src="video.thumbnail"/><video v-else-if="video.stream" :src="video.stream" muted preload="metadata"/><Play/></div><strong>{{video.caption||'SportUniverse video'}}</strong><small>{{video.creator.name}} · {{video.views}} views</small></a></div></section>
<section v-if="(active==='all'||active==='clubs')&&payload.data.clubs?.length" class="discovery-group"><header><h2><Users/>Clubs & academies</h2><button @click="active='clubs'">View all</button></header><div class="account-grid"><article v-for="club in payload.data.clubs"><span>{{club.name.slice(0,2).toUpperCase()}}</span><div><Link :href="'/@'+club.slug">{{club.name}}</Link><small>{{club.city||'South Africa'}}</small><p>{{club.bio}}</p></div></article></div></section>
<section v-if="(active==='all'||active==='opportunities')&&payload.data.opportunities?.length" class="discovery-group"><header><h2><BriefcaseBusiness/>Opportunities</h2><Link href="/opportunities">View all</Link></header><div class="discovery-opps"><Link v-for="item in payload.data.opportunities" href="/opportunities"><span>{{item.type.replaceAll('_',' ')}}</span><strong>{{item.title}}</strong><small>{{[item.poster,item.sport,item.city].filter(Boolean).join(' · ')}}</small><p>{{item.description}}</p></Link></div></section>
<template v-if="!query.trim()"><section v-if="payload.discovery.trending_hashtags?.length" class="discovery-group"><header><h2><Flame/>Trending hashtags</h2></header><div class="trend-tags"><button v-for="tag in payload.discovery.trending_hashtags" @click="useSearch('#'+tag.tag)">#{{tag.tag}}<small>{{tag.posts}} posts</small></button></div></section><section v-if="payload.discovery.nearby?.city" class="discovery-group"><header><h2><MapPin/>Near {{payload.discovery.nearby.city}}</h2></header><div class="nearby-split"><div><h3>Athletes</h3><Link v-for="person in payload.discovery.nearby.athletes" :href="'/@'+person.slug">{{person.name}}<small>{{person.sport}}</small></Link></div><div><h3>Opportunities</h3><Link v-for="item in payload.discovery.nearby.opportunities" href="/opportunities">{{item.title}}<small>{{item.sport}}</small></Link></div></div></section><section v-if="payload.discovery.recommended_accounts?.length" class="discovery-group"><header><h2><UserPlus/>Recommended accounts</h2></header><div class="account-grid"><article v-for="person in payload.discovery.recommended_accounts"><span>{{person.name.slice(0,2).toUpperCase()}}</span><div><Link :href="'/@'+person.slug">{{person.name}}</Link><small>{{person.sport||person.roles?.[0]}} · {{person.followers}} followers</small></div><button @click="follow(person)"><UserPlus/></button></article></div></section></template>
<section v-if="!resultCount&&query" class="discover-empty"><Search/><h2>No results found</h2><p>Try another name, city, sport or keyword.</p></section></template></main></AppShell></template>
