import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '../../src/api/client';
import { PrimaryButton } from '../../src/components/PrimaryButton';
import { colors, radius, spacing } from '../../src/theme';
import type { Opportunity, Sport } from '../../src/types/api';

const types = ['trial', 'job', 'training_camp', 'sponsorship', 'scout_day', 'academy_application'] as const;
const initial = { title: '', type: 'trial', description: '', sport_id: 0, position_id: 0, country: 'ZA', province: '', city: '', is_remote: false, minimum_age: '', maximum_age: '', requirements: '', deadline: '' };
export default function OpportunityEditorScreen() {
  const { id } = useLocalSearchParams<{ id?: string }>();
  const editing = Boolean(id);
  const client = useQueryClient();
  const [form, setForm] = useState(initial);
  const existing = useQuery({ queryKey: ['opportunity', id], enabled: editing, queryFn: async () => (await api.get('/opportunities/' + id)).data.data as Opportunity });
  const sports = useQuery({ queryKey: ['sports'], queryFn: async () => (await api.get('/sports')).data.data as Sport[] });
  useEffect(() => { const item = existing.data; if (!item) return; setForm({ title: item.title, type: item.type, description: item.description, sport_id: item.sport?.id ?? 0, position_id: item.position?.id ?? 0, country: item.location.country ?? 'ZA', province: item.location.province ?? '', city: item.location.city ?? '', is_remote: item.location.is_remote, minimum_age: String(item.age_range.minimum ?? ''), maximum_age: String(item.age_range.maximum ?? ''), requirements: item.requirements.join('\n'), deadline: item.deadline ? item.deadline.slice(0, 10) : '' }); }, [existing.data]);
  const positions = useMemo(() => sports.data?.find(sport => sport.id === form.sport_id)?.positions ?? [], [sports.data, form.sport_id]);
  const submit = useMutation({ mutationFn: async (publish: boolean) => { const payload = { ...form, sport_id: form.sport_id || null, position_id: form.position_id || null, minimum_age: form.minimum_age ? Number(form.minimum_age) : null, maximum_age: form.maximum_age ? Number(form.maximum_age) : null, requirements: form.requirements.split('\n').map(value => value.trim()).filter(Boolean), deadline: form.deadline ? `${form.deadline}T23:59:59+02:00` : null, publish }; return editing ? api.patch('/opportunities/' + id, payload) : api.post('/opportunities', payload); }, onSuccess: async (_, published) => { await Promise.all([client.invalidateQueries({ queryKey: ['opportunities'] }), client.invalidateQueries({ queryKey: ['opportunities', 'mine'] })]); Alert.alert(published ? 'Opportunity published' : 'Draft saved', published ? 'Athletes can now discover and apply.' : 'You can finish and publish it later.', [{ text: 'Done', onPress: () => router.replace('/opportunity/manage') }]); }, onError: (error: any) => Alert.alert('Opportunity not saved', firstError(error)) });
  const chooseFinish = () => Alert.alert('Save opportunity', 'Publish now or keep this as a draft?', [{ text: 'Cancel', style: 'cancel' }, { text: 'Save draft', onPress: () => submit.mutate(false) }, { text: 'Publish', onPress: () => submit.mutate(true) }]);
  const update = (key: string, value: any) => setForm(current => ({ ...current, [key]: value }));
  const ready = form.title.trim() && form.description.trim() && form.type;

  if (editing && existing.isLoading) return <SafeAreaView style={styles.safe}><TopBar title="Edit opportunity" /><ActivityIndicator style={{ flex: 1 }} color={colors.blue} /></SafeAreaView>;
  return <SafeAreaView edges={['top']} style={styles.safe}><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><TopBar title={editing ? 'Edit opportunity' : 'Create opportunity'} /><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Field label="Title" value={form.title} onChangeText={value => update('title', value)} maxLength={200} /><Text style={styles.label}>Opportunity type</Text><View style={styles.chips}>{types.map(value => <Chip key={value} label={value.replaceAll('_', ' ')} selected={form.type === value} onPress={() => update('type', value)} />)}</View><Field label="Description" value={form.description} onChangeText={value => update('description', value)} multiline maxLength={20000} /><Text style={styles.label}>Sport</Text><View style={styles.chips}>{(sports.data ?? []).map(sport => <Chip key={sport.id} label={sport.name} selected={form.sport_id === sport.id} onPress={() => setForm(current => ({ ...current, sport_id: sport.id, position_id: 0 }))} />)}</View>{positions.length ? <><Text style={styles.label}>Position</Text><View style={styles.chips}>{positions.map(position => <Chip key={position.id} label={position.name} selected={form.position_id === position.id} onPress={() => update('position_id', position.id)} />)}</View></> : null}<View style={styles.remote}><View><Text style={styles.remoteTitle}>Remote opportunity</Text><Text style={styles.remoteCopy}>Applicants do not need to attend a location.</Text></View><Switch value={form.is_remote} onValueChange={value => update('is_remote', value)} trackColor={{ false: colors.surfaceRaised, true: colors.blue }} /></View>{!form.is_remote ? <><Field label="Country code" value={form.country} onChangeText={value => update('country', value.toUpperCase().slice(0, 2))} maxLength={2} /><Field label="Province" value={form.province} onChangeText={value => update('province', value)} /><Field label="City" value={form.city} onChangeText={value => update('city', value)} /></> : null}<View style={styles.columns}><Field boxStyle={styles.column} label="Minimum age" value={form.minimum_age} onChangeText={value => update('minimum_age', value.replace(/\D/g, ''))} keyboardType="number-pad" /><Field boxStyle={styles.column} label="Maximum age" value={form.maximum_age} onChangeText={value => update('maximum_age', value.replace(/\D/g, ''))} keyboardType="number-pad" /></View><Field label="Application deadline" value={form.deadline} onChangeText={value => update('deadline', value)} placeholder="YYYY-MM-DD" /><Field label="Requirements" value={form.requirements} onChangeText={value => update('requirements', value)} placeholder="Enter one requirement per line" multiline /><PrimaryButton label={editing ? 'Save opportunity' : 'Continue'} loading={submit.isPending} disabled={!ready} onPress={chooseFinish} style={{ marginTop: 25 }} /></ScrollView></KeyboardAvoidingView></SafeAreaView>;
}

function TopBar({ title }: { title: string }) { return <View style={styles.header}><Pressable accessibilityLabel="Go back" hitSlop={12} onPress={() => router.back()}><Ionicons name="chevron-back" size={26} color="#fff" /></Pressable><Text style={styles.headerTitle}>{title}</Text><View style={{ width: 26 }} /></View>; }
function Field({ label, multiline, boxStyle, ...props }: { label: string; multiline?: boolean; boxStyle?: any } & React.ComponentProps<typeof TextInput>) { return <View style={boxStyle}><Text style={styles.label}>{label}</Text><TextInput {...props} multiline={multiline} placeholderTextColor="#71849B" style={[styles.input, multiline && styles.textarea]} textAlignVertical={multiline ? 'top' : 'center'} /></View>; }
function Chip({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={[styles.chip, selected && styles.chipActive]}><Text style={[styles.chipText, selected && { color: '#fff' }]}>{label}</Text></Pressable>; }
function firstError(error: any) { return Object.values(error?.response?.data?.errors || {}).flat()?.[0] as string || error?.response?.data?.message || 'Check the information and try again.'; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.navy }, flex: { flex: 1 }, header: { height: 56, paddingHorizontal: spacing.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.line }, headerTitle: { color: '#fff', fontSize: 17, fontWeight: '900' }, content: { padding: spacing.lg, paddingBottom: 45 }, label: { color: '#DCE7F5', fontSize: 12, fontWeight: '800', marginTop: 18, marginBottom: 7 }, input: { minHeight: 50, paddingHorizontal: 14, borderRadius: radius.md, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface, color: '#fff' }, textarea: { height: 120, paddingTop: 13 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, chip: { paddingHorizontal: 12, paddingVertical: 9, borderRadius: radius.pill, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface }, chipActive: { borderColor: colors.blue, backgroundColor: colors.blue }, chipText: { color: colors.muted, fontSize: 11, fontWeight: '800', textTransform: 'capitalize' }, remote: { marginTop: 22, padding: spacing.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderRadius: radius.md, backgroundColor: colors.surface }, remoteTitle: { color: '#fff', fontSize: 13, fontWeight: '900' }, remoteCopy: { color: colors.muted, fontSize: 10, marginTop: 3 }, columns: { flexDirection: 'row', gap: 10 }, column: { flex: 1 } });
