import { Linking, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import * as WebBrowser from 'expo-web-browser';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api } from '../../src/api/client';
import { colors, radius, spacing } from '../../src/theme';

export default function AboutScreen() {
  const origin = (api.defaults.baseURL || 'https://sportsuniverse.co.za/api/v1').replace(/\/api\/v1\/?$/, '');
  return <SafeAreaView edges={['top']} style={styles.safe}><View style={styles.header}><Pressable accessibilityLabel="Go back" onPress={() => router.back()}><Ionicons name="chevron-back" size={26} color="#fff" /></Pressable><Text style={styles.headerTitle}>About & privacy</Text><View style={{ width: 26 }} /></View><ScrollView contentContainerStyle={styles.content}><View style={styles.hero}><Ionicons name="trophy" size={36} color={colors.blue} /><Text style={styles.title}>Talent deserves to be discovered.</Text><Text style={styles.copy}>SportsUniverse is a sporting community where athletes showcase their ability, supporters discover talent, and clubs, scouts and organisations create meaningful opportunities.</Text></View><Info icon="play-outline" title="Show your game" copy="Publish sporting highlights and build a profile that represents your journey, achievements and potential." /><Info icon="people-outline" title="Build connections" copy="Follow athletes, engage with sporting communities and connect with people who can help move careers forward." /><Info icon="briefcase-outline" title="Find opportunities" copy="Discover trials, camps, scout days, jobs, sponsorships and development programmes across sport." /><Info icon="shield-checkmark-outline" title="Participate safely" copy="Privacy controls, reporting and moderation tools help keep participation respectful and secure." /><Text style={styles.sectionTitle}>Legal and support</Text><LinkRow icon="lock-closed-outline" title="Privacy Policy" copy="How SportsUniverse collects, uses and protects information." onPress={() => WebBrowser.openBrowserAsync(origin + '/privacy-policy')} /><LinkRow icon="globe-outline" title="About SportsUniverse" copy="Read the complete public About page." onPress={() => WebBrowser.openBrowserAsync(origin + '/about')} /><LinkRow icon="mail-outline" title="Contact support" copy="support@sportsuniverse.co.za" onPress={() => Linking.openURL('mailto:support@sportsuniverse.co.za?subject=SportsUniverse%20Mobile%20Support')} /><Text style={styles.footer}>Talent. Opportunity. Community.</Text></ScrollView></SafeAreaView>;
}
function Info({ icon, title, copy }: { icon: keyof typeof Ionicons.glyphMap; title: string; copy: string }) { return <View style={styles.info}><View style={styles.icon}><Ionicons name={icon} size={22} color="#79A3FF" /></View><View style={{ flex: 1 }}><Text style={styles.infoTitle}>{title}</Text><Text style={styles.infoCopy}>{copy}</Text></View></View>; }
function LinkRow({ icon, title, copy, onPress }: { icon: keyof typeof Ionicons.glyphMap; title: string; copy: string; onPress: () => void }) { return <Pressable onPress={onPress} style={styles.link}><Ionicons name={icon} size={22} color="#79A3FF" /><View style={{ flex: 1 }}><Text style={styles.infoTitle}>{title}</Text><Text style={styles.linkCopy}>{copy}</Text></View><Ionicons name="open-outline" size={17} color={colors.muted} /></Pressable>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.navy }, header: { height: 56, paddingHorizontal: spacing.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.line }, headerTitle: { color: '#fff', fontSize: 17, fontWeight: '900' }, content: { padding: spacing.md, paddingBottom: 50 }, hero: { padding: spacing.lg, borderRadius: radius.lg, backgroundColor: '#102D4B', alignItems: 'center' }, title: { color: '#fff', fontSize: 25, lineHeight: 30, fontWeight: '900', textAlign: 'center', marginTop: 13 }, copy: { color: '#C6D4E2', fontSize: 12, lineHeight: 19, textAlign: 'center', marginTop: 9 }, info: { padding: spacing.md, marginTop: 10, flexDirection: 'row', gap: 12, borderWidth: 1, borderColor: colors.line, borderRadius: radius.lg, backgroundColor: colors.surface }, icon: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surfaceRaised }, infoTitle: { color: '#fff', fontSize: 13, fontWeight: '900' }, infoCopy: { color: colors.muted, fontSize: 10, lineHeight: 16, marginTop: 5 }, sectionTitle: { color: '#fff', fontSize: 18, fontWeight: '900', marginTop: 24, marginBottom: 10 }, link: { minHeight: 70, marginBottom: 9, padding: 13, flexDirection: 'row', alignItems: 'center', gap: 11, borderWidth: 1, borderColor: colors.line, borderRadius: radius.lg, backgroundColor: colors.surface }, linkCopy: { color: colors.muted, fontSize: 10, marginTop: 4 }, footer: { color: colors.muted, textAlign: 'center', fontSize: 10, marginTop: 24 } });
