import { useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '../../src/api/client';
import { PrimaryButton } from '../../src/components/PrimaryButton';
import { colors, radius, spacing } from '../../src/theme';

type Request = { status: string; requested_at: string; scheduled_for: string; reason?: string | null } | null;

export default function AccountDeletionScreen() {
  const client = useQueryClient();
  const [confirmation, setConfirmation] = useState('');
  const [reason, setReason] = useState('');
  const request = useQuery({ queryKey: ['account-deletion'], queryFn: async () => (await api.get<{ data: Request }>('/auth/account-deletion')).data.data });
  const submit = useMutation({ mutationFn: () => api.post('/auth/account-deletion', { confirmation, reason: reason.trim() || null }), onSuccess: response => { client.invalidateQueries({ queryKey: ['account-deletion'] }); client.invalidateQueries({ queryKey: ['profile'] }); setConfirmation(''); Alert.alert('Deletion requested', response.data.message); }, onError: error => Alert.alert('Request not submitted', message(error)) });
  const cancel = useMutation({ mutationFn: () => api.delete('/auth/account-deletion'), onSuccess: response => { client.invalidateQueries({ queryKey: ['account-deletion'] }); Alert.alert('Request cancelled', response.data.message); }, onError: error => Alert.alert('Request not cancelled', message(error)) });
  const pending = request.data?.status === 'pending';
  const confirmCancel = () => Alert.alert('Cancel deletion request?', 'Your account will remain active, but you must manually restore profile visibility if desired.', [{ text: 'Keep request', style: 'cancel' }, { text: 'Cancel request', onPress: () => cancel.mutate() }]);
  return <SafeAreaView edges={['top']} style={styles.safe}><KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={styles.header}><Pressable accessibilityLabel="Go back" onPress={() => router.back()}><Ionicons name="chevron-back" size={26} color="#fff" /></Pressable><Text style={styles.headerTitle}>Delete account</Text><View style={{ width: 26 }} /></View><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">{pending ? <View style={styles.pending}><Ionicons name="time-outline" size={38} color={colors.orange} /><Text style={styles.title}>Deletion is scheduled</Text><Text style={styles.copy}>Your profile is private. Your account and eligible personal data are scheduled for deletion by {new Date(request.data!.scheduled_for).toLocaleDateString()}.</Text>{request.data?.reason ? <Text style={styles.reason}>Reason: {request.data.reason}</Text> : null}<PrimaryButton label="Cancel deletion request" secondary loading={cancel.isPending} onPress={confirmCancel} style={{ width: '100%', marginTop: 20 }} /></View> : <><View style={styles.warning}><Ionicons name="warning-outline" size={34} color={colors.danger} /><Text style={styles.title}>Request permanent deletion</Text><Text style={styles.copy}>Your profile will immediately become private. After the 30-day cancellation period, your account and eligible personal data will be permanently removed.</Text></View><View style={styles.list}><Point text="Your public profile and availability will be disabled immediately." /><Point text="Posts, messages, applications and documents may be removed or anonymised." /><Point text="Some records may be retained where legally required or needed for safety." /><Point text="You can cancel the request before the scheduled deletion date." /></View><Text style={styles.label}>Why are you leaving? (optional)</Text><TextInput value={reason} onChangeText={setReason} multiline maxLength={2000} placeholder="Help us understand how SportUniverse can improve…" placeholderTextColor={colors.muted} style={styles.textarea} /><Text style={styles.label}>Type DELETE to confirm</Text><TextInput value={confirmation} onChangeText={setConfirmation} autoCapitalize="characters" autoCorrect={false} placeholder="DELETE" placeholderTextColor={colors.muted} style={styles.input} /><PrimaryButton label="Request account deletion" loading={submit.isPending} disabled={confirmation !== 'DELETE'} onPress={() => submit.mutate()} style={{ marginTop: 18 }} /></>}</ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
function Point({ text }: { text: string }) { return <View style={styles.point}><Ionicons name="remove-circle-outline" size={18} color={colors.danger} /><Text style={styles.pointText}>{text}</Text></View>; }
function message(error: any) { return error?.response?.data?.message || Object.values(error?.response?.data?.errors || {}).flat()[0] as string || 'Please try again.'; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.navy }, header: { height: 56, paddingHorizontal: spacing.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.line }, headerTitle: { color: '#fff', fontSize: 17, fontWeight: '900' }, content: { padding: spacing.lg, paddingBottom: 50 }, warning: { alignItems: 'center', padding: spacing.lg, borderWidth: 1, borderColor: 'rgba(255,107,129,.28)', borderRadius: radius.lg, backgroundColor: 'rgba(255,107,129,.07)' }, pending: { alignItems: 'center', padding: spacing.lg, borderWidth: 1, borderColor: 'rgba(255,176,32,.3)', borderRadius: radius.lg, backgroundColor: 'rgba(255,176,32,.07)' }, title: { color: '#fff', fontSize: 22, fontWeight: '900', textAlign: 'center', marginTop: 12 }, copy: { color: '#C8D4E1', fontSize: 12, lineHeight: 19, textAlign: 'center', marginTop: 8 }, reason: { color: colors.muted, fontSize: 10, marginTop: 14 }, list: { gap: 11, marginVertical: 20 }, point: { flexDirection: 'row', alignItems: 'flex-start', gap: 9 }, pointText: { flex: 1, color: colors.muted, fontSize: 11, lineHeight: 17 }, label: { color: '#DCE7F5', fontSize: 11, fontWeight: '900', marginTop: 14, marginBottom: 7 }, input: { minHeight: 50, paddingHorizontal: 14, color: '#fff', borderWidth: 1, borderColor: colors.line, borderRadius: radius.md, backgroundColor: colors.surface }, textarea: { height: 115, padding: 13, color: '#fff', textAlignVertical: 'top', borderWidth: 1, borderColor: colors.line, borderRadius: radius.md, backgroundColor: colors.surface } });
