import { useState } from 'react';
import { ActivityIndicator, Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '../../src/api/client';
import { PrimaryButton } from '../../src/components/PrimaryButton';
import { useAuthStore } from '../../src/stores/auth';
import { colors, radius, spacing } from '../../src/theme';
import type { ApiResponse, Profile } from '../../src/types/api';

export default function SettingsScreen() {
  const { logout } = useAuthStore();
  const queryClient = useQueryClient();
  const [passwords, setPasswords] = useState({ current_password: '', password: '', password_confirmation: '' });
  const [visible, setVisible] = useState<string>();
  const profile = useQuery({ queryKey: ['profile', 'mine'], queryFn: async () => (await api.get<ApiResponse<Profile>>('/profile')).data.data });
  const privacy = useMutation({ mutationFn: async (change: { is_public?: boolean; is_available?: boolean }) => (await api.patch('/profile', change)).data.data as Profile, onSuccess: data => queryClient.setQueryData(['profile', 'mine'], data), onError: (error: any) => Alert.alert('Setting not saved', error?.response?.data?.message || 'Please try again.') });
  const password = useMutation({
    mutationFn: async () => (await api.put('/auth/password', passwords)).data.message as string,
    onSuccess: message => { setPasswords({ current_password: '', password: '', password_confirmation: '' }); Alert.alert('Password changed', message); },
    onError: (error: any) => Alert.alert('Password not changed', firstError(error)),
  });
  const confirmSignOut = () => Alert.alert('Sign out?', 'You can sign back in at any time.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Sign out', style: 'destructive', onPress: async () => { await logout(); router.replace('/(tabs)/feed'); } }]);
  const passwordReady = passwords.current_password.length > 0 && passwords.password.length >= 8 && passwords.password_confirmation === passwords.password;

  return <SafeAreaView edges={['top']} style={styles.safe}><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={styles.header}><Pressable accessibilityLabel="Go back" hitSlop={12} onPress={() => router.back()}><Ionicons name="chevron-back" size={26} color="#fff" /></Pressable><Text style={styles.headerTitle}>Settings</Text><View style={{ width: 26 }} /></View><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
    <Text style={styles.sectionTitle}>Privacy and availability</Text><View style={styles.card}>{profile.isLoading ? <ActivityIndicator style={styles.loader} color={colors.blue} /> : <><SettingToggle icon="globe-outline" title="Public profile" description="Allow people to discover and view your profile." value={profile.data?.is_public ?? true} disabled={privacy.isPending} onChange={value => privacy.mutate({ is_public: value })} /><View style={styles.divider} /><SettingToggle icon="flash-outline" title="Available for opportunities" description="Show recruiters and clubs that you are available." value={profile.data?.is_available ?? false} disabled={privacy.isPending} onChange={value => privacy.mutate({ is_available: value })} /></>}</View>
    <Text style={styles.sectionTitle}>Notifications</Text><Pressable onPress={() => router.push('/notifications/preferences')} style={styles.linkRow}><View style={styles.rowIcon}><Ionicons name="notifications-outline" size={20} color="#79A3FF" /></View><View style={styles.rowCopy}><Text style={styles.rowTitle}>Notification preferences</Text><Text style={styles.rowDescription}>Choose which updates reach you.</Text></View><Ionicons name="chevron-forward" size={20} color={colors.muted} /></Pressable>
    <Text style={styles.sectionTitle}>Safety</Text><Pressable onPress={() => router.push('/settings/blocked-users')} style={styles.linkRow}><View style={styles.rowIcon}><Ionicons name="person-remove-outline" size={20} color="#79A3FF" /></View><View style={styles.rowCopy}><Text style={styles.rowTitle}>Blocked users</Text><Text style={styles.rowDescription}>Review and unblock people you have blocked.</Text></View><Ionicons name="chevron-forward" size={20} color={colors.muted} /></Pressable>
    <Text style={styles.sectionTitle}>Security</Text><View style={styles.card}><PasswordField label="Current password" field="current_password" value={passwords.current_password} visible={visible} onToggle={setVisible} onChange={value => setPasswords(current => ({ ...current, current_password: value }))} /><PasswordField label="New password" field="password" value={passwords.password} visible={visible} onToggle={setVisible} onChange={value => setPasswords(current => ({ ...current, password: value }))} /><PasswordField label="Confirm new password" field="password_confirmation" value={passwords.password_confirmation} visible={visible} onToggle={setVisible} onChange={value => setPasswords(current => ({ ...current, password_confirmation: value }))} /><Text style={styles.hint}>Use at least 8 characters. Changing it logs out your other devices.</Text><PrimaryButton label="Change password" loading={password.isPending} onPress={() => password.mutate()} disabled={!passwordReady} style={{ marginTop: 16 }} /></View>
    <Text style={styles.sectionTitle}>Account</Text><Pressable onPress={confirmSignOut} style={styles.signOut}><Ionicons name="log-out-outline" size={21} color={colors.danger} /><Text style={styles.signOutText}>Sign out of this device</Text></Pressable>
  </ScrollView></KeyboardAvoidingView></SafeAreaView>;
}

function SettingToggle({ icon, title, description, value, disabled, onChange }: { icon: keyof typeof Ionicons.glyphMap; title: string; description: string; value: boolean; disabled: boolean; onChange: (value: boolean) => void }) { return <View style={styles.toggleRow}><View style={styles.rowIcon}><Ionicons name={icon} size={20} color="#79A3FF" /></View><View style={styles.rowCopy}><Text style={styles.rowTitle}>{title}</Text><Text style={styles.rowDescription}>{description}</Text></View><Switch value={value} disabled={disabled} onValueChange={onChange} trackColor={{ false: colors.surfaceRaised, true: colors.blue }} /></View>; }
function PasswordField({ label, field, value, visible, onToggle, onChange }: { label: string; field: string; value: string; visible?: string; onToggle: (field?: string) => void; onChange: (value: string) => void }) { const shown = visible === field; return <View style={styles.field}><Text style={styles.label}>{label}</Text><View style={styles.passwordWrap}><TextInput value={value} onChangeText={onChange} secureTextEntry={!shown} autoCapitalize="none" autoCorrect={false} style={styles.input} /><Pressable accessibilityLabel={shown ? 'Hide password' : 'Show password'} hitSlop={10} onPress={() => onToggle(shown ? undefined : field)}><Ionicons name={shown ? 'eye-off-outline' : 'eye-outline'} size={21} color={colors.muted} /></Pressable></View></View>; }
function firstError(error: any) { return Object.values(error?.response?.data?.errors || {}).flat()?.[0] as string || error?.response?.data?.message || 'Please check your passwords and try again.'; }

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.navy }, flex: { flex: 1 }, header: { height: 56, paddingHorizontal: spacing.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.line }, headerTitle: { color: '#fff', fontSize: 18, fontWeight: '900' }, content: { padding: spacing.lg, paddingBottom: 50 }, sectionTitle: { color: colors.muted, fontSize: 11, fontWeight: '900', letterSpacing: .8, textTransform: 'uppercase', marginTop: 22, marginBottom: 9 }, card: { padding: spacing.md, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface }, loader: { height: 110 }, toggleRow: { minHeight: 66, flexDirection: 'row', alignItems: 'center', gap: 11 }, rowIcon: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surfaceRaised }, rowCopy: { flex: 1 }, rowTitle: { color: '#fff', fontSize: 14, fontWeight: '800' }, rowDescription: { color: colors.muted, fontSize: 11, lineHeight: 16, marginTop: 3 }, divider: { height: 1, marginVertical: 5, backgroundColor: colors.line }, linkRow: { minHeight: 72, padding: spacing.md, flexDirection: 'row', alignItems: 'center', gap: 11, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface }, field: { marginBottom: 13 }, label: { color: '#DCE7F5', fontSize: 12, fontWeight: '800', marginBottom: 7 }, passwordWrap: { height: 50, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', borderRadius: radius.md, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.navyLight }, input: { flex: 1, height: '100%', color: '#fff' }, hint: { color: colors.muted, fontSize: 11, lineHeight: 16 }, signOut: { minHeight: 58, paddingHorizontal: spacing.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9, borderRadius: radius.md, borderWidth: 1, borderColor: 'rgba(255,107,129,.3)', backgroundColor: 'rgba(255,107,129,.08)' }, signOutText: { color: colors.danger, fontWeight: '800' } });
