import { useEffect, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { api } from '../../src/api/client';
import { PrimaryButton } from '../../src/components/PrimaryButton';
import { useAuthStore } from '../../src/stores/auth';
import { colors, radius, spacing } from '../../src/theme';

export default function VerifyEmailScreen() {
  const link = useLocalSearchParams<{ id?: string; hash?: string; expires?: string; signature?: string }>();
  const user = useAuthStore(state => state.user); const [busy, setBusy] = useState(false); const [checking, setChecking] = useState(false);
  useEffect(() => { if (!link.id || !link.hash || !link.expires || !link.signature) return; let active = true; setChecking(true); api.get(`/auth/email/verify/${encodeURIComponent(link.id)}/${encodeURIComponent(link.hash)}`, { params: { expires: link.expires, signature: link.signature } }).then(async response => { const me = await api.get('/me'); if (!active) return; useAuthStore.setState({ user: me.data.data }); Alert.alert('Email verified', response.data.message); }).catch((error: any) => { if (active) Alert.alert('Verification failed', error?.response?.data?.message || 'This verification link may have expired. Request a new one.'); }).finally(() => { if (active) setChecking(false); }); return () => { active = false; }; }, [link.id, link.hash, link.expires, link.signature]);
  const resend = async () => { setBusy(true); try { const response = await api.post('/auth/email/verification-notification'); Alert.alert('Verification email', response.data.message); } catch (error: any) { Alert.alert('Email not sent', error?.response?.data?.message || 'Please wait and try again.'); } finally { setBusy(false); } };
  const refresh = async () => { setChecking(true); try { const response = await api.get('/me'); useAuthStore.setState({ user: response.data.data }); if (response.data.data.email_verified) Alert.alert('Email verified', 'Your recovery email is confirmed.'); else Alert.alert('Not verified yet', 'Open the link in your email, then check again.'); } catch { Alert.alert('Could not check', 'Check your connection and try again.'); } finally { setChecking(false); } };
  return <SafeAreaView edges={['top']} style={styles.safe}><View style={styles.header}><Pressable accessibilityLabel="Go back" onPress={() => router.back()}><Ionicons name="chevron-back" size={26} color="#fff" /></Pressable><Text style={styles.headerTitle}>Verify email</Text><View style={{ width: 26 }} /></View><View style={styles.content}><View style={[styles.icon, user?.email_verified && styles.iconDone]}><Ionicons name={user?.email_verified ? 'checkmark-circle' : 'mail-unread-outline'} size={42} color={user?.email_verified ? colors.green : '#79A3FF'} /></View><Text style={styles.title}>{user?.email_verified ? 'Email verified' : 'Confirm your email address'}</Text><Text style={styles.email}>{user?.email}</Text><Text style={styles.copy}>{user?.email_verified ? 'Your recovery email is confirmed and can be used securely for password resets.' : 'Select the verification link sent to your inbox. It protects account recovery and important security notifications.'}</Text>{!user?.email_verified ? <><PrimaryButton label="Resend verification email" loading={busy} onPress={resend} style={{ width: '100%', marginTop: 24 }} /><PrimaryButton label="I have verified — check again" secondary loading={checking} onPress={refresh} style={{ width: '100%', marginTop: 10 }} /></> : <PrimaryButton label="Done" onPress={() => router.back()} style={{ width: '100%', marginTop: 24 }} />}</View></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.navy }, header: { height: 56, paddingHorizontal: spacing.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.line }, headerTitle: { color: '#fff', fontSize: 17, fontWeight: '900' }, content: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: spacing.xl }, icon: { width: 82, height: 82, borderRadius: 41, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(71,111,234,.14)' }, iconDone: { backgroundColor: 'rgba(119,165,113,.12)' }, title: { color: '#fff', fontSize: 25, fontWeight: '900', textAlign: 'center', marginTop: 18 }, email: { color: '#79A3FF', fontSize: 13, fontWeight: '800', marginTop: 7 }, copy: { color: colors.muted, fontSize: 13, lineHeight: 20, textAlign: 'center', marginTop: 12, maxWidth: 350 } });
