import { Pressable, StyleSheet, Text, View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import { colors, radius } from '../theme';
import type { Video } from '../types/api';

const compact=(n:number)=>Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(n||0);
export function FeedCard({video,height,onProtectedAction,index}: {video:Video;height:number;onProtectedAction:()=>void;index:number}){
  const glow=index%3===0?'#245FA1':index%3===1?'#783A74':'#176B58';
  const action=(icon:any,value:string)=> <Pressable style={styles.action} onPress={onProtectedAction}><View style={styles.actionCircle}><Ionicons name={icon} size={23} color="#fff"/></View><Text style={styles.actionText}>{value}</Text></Pressable>;
  return <View style={[styles.card,{height}]}><LinearGradient colors={[glow,'#122239','#04090F']} locations={[0,.55,1]} style={StyleSheet.absoluteFill}/><View style={styles.person}><View style={styles.head}/><View style={styles.body}/></View><View style={styles.badge}><Text style={styles.badgeText}>{index===0?'HIGHLIGHT':'FOR YOU'}</Text></View><View style={styles.copy}><View style={styles.nameRow}><View style={styles.avatar}><Text style={styles.avatarText}>{video.creator.name[0]}</Text></View><View style={{flex:1}}><Text style={styles.name}>{video.creator.name} <Ionicons name="checkmark-circle" color="#76A5FF" size={16}/></Text><Text style={styles.meta}>{video.creator.sport||'Athlete'} · {video.creator.position||'Rising talent'} · {video.creator.city||'South Africa'}</Text></View><Pressable style={styles.follow} onPress={onProtectedAction}><Text style={styles.followText}>Follow</Text></Pressable></View><Text style={styles.caption}>{video.caption}</Text><Text style={styles.tags}>{video.hashtags.map(tag=>`#${tag}`).join('  ')}</Text></View><View style={styles.rail}>{action('heart',compact(video.counts.likes))}{action('chatbubble',compact(video.counts.comments))}{action('paper-plane',compact(video.counts.shares))}{action('bookmark',compact(video.counts.saves))}{action('person-add','Request')}</View></View>;
}
const styles=StyleSheet.create({card:{width:'100%',backgroundColor:'#07101B',overflow:'hidden'},person:{position:'absolute',top:'18%',left:'21%',right:'22%',height:'53%',alignItems:'center',opacity:.5},head:{width:92,height:92,borderRadius:46,backgroundColor:'#7692AF'},body:{width:'100%',height:'80%',marginTop:-8,borderTopLeftRadius:90,borderTopRightRadius:90,backgroundColor:'#243B52'},badge:{position:'absolute',top:18,left:16,paddingHorizontal:10,paddingVertical:6,borderRadius:radius.pill,backgroundColor:colors.pink},badgeText:{color:'#fff',fontSize:10,fontWeight:'900',letterSpacing:.5},copy:{position:'absolute',left:16,right:76,bottom:24},nameRow:{flexDirection:'row',alignItems:'center',gap:9},avatar:{width:42,height:42,borderRadius:21,alignItems:'center',justifyContent:'center',backgroundColor:colors.blue},avatarText:{color:'#fff',fontWeight:'900',fontSize:17},name:{color:'#fff',fontSize:17,fontWeight:'900'},meta:{color:'#C3D0DE',fontSize:11,marginTop:2},follow:{paddingHorizontal:12,paddingVertical:7,borderRadius:10,backgroundColor:colors.blue},followText:{color:'#fff',fontSize:11,fontWeight:'800'},caption:{color:'#fff',fontSize:14,lineHeight:20,marginTop:12},tags:{color:'#8EB0FF',fontWeight:'700',fontSize:12,marginTop:7},rail:{position:'absolute',right:12,bottom:20,gap:12},action:{alignItems:'center'},actionCircle:{width:45,height:45,borderRadius:23,backgroundColor:'rgba(5,12,20,.66)',borderWidth:1,borderColor:'rgba(255,255,255,.15)',alignItems:'center',justifyContent:'center'},actionText:{color:'#fff',fontSize:10,fontWeight:'700',marginTop:3}});
