<script setup lang="ts">
import { Head, Link } from '@inertiajs/vue3';
import { ArrowLeft, Check, ChevronRight, Eye, MousePointerClick, Play, Sparkles, Users } from '@lucide/vue';
import { computed, onMounted, ref } from 'vue';
import AppShell from '../../Layouts/AppShell.vue';
const videos=ref<any[]>([]),selected=ref<any>(),loading=ref(true),step=ref(1),goal=ref('views'),audience=ref('automatic'),budget=ref(100),days=ref(3),notice=ref('');
const goals=[{id:'views',label:'More video views',hint:'Reach people likely to watch',icon:Eye},{id:'followers',label:'More followers',hint:'Grow your sports audience',icon:Users},{id:'website',label:'More website visits',hint:'Drive traffic to your destination',icon:MousePointerClick}];
const total=computed(()=>budget.value*days.value),reach=computed(()=>[total.value*18,total.value*31]);
const money=(v:number)=>new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR',maximumFractionDigits:0}).format(v);
const save=()=>{localStorage.setItem('sportuniverse:promotion-draft',JSON.stringify({video_id:selected.value.id,goal:goal.value,audience:audience.value,daily_budget:budget.value,duration_days:days.value}));notice.value='Promotion draft saved. Connect a payment provider to activate it.'};
onMounted(async()=>{const r=await fetch('/api/v1/videos/mine',{credentials:'same-origin',headers:{Accept:'application/json'}}),p=await r.json();videos.value=p.data??[];loading.value=false});
</script>
<template><Head title="Promote"/><AppShell><main class="promote-page"><header class="promote-head"><Link href="/feed"><ArrowLeft/></Link><div><h1>Promote</h1><p>Reach more people with your sports content.</p></div><span>Step {{step}} of 4</span></header><div class="promote-progress"><i v-for="n in 4" :class="{on:n<=step}"/></div>
<section v-if="step===1" class="promote-card"><h2>Choose a post</h2><p>Select the video you want to promote.</p><div v-if="loading" class="promote-empty">Loading your posts…</div><div v-else-if="videos.length" class="promote-videos"><button v-for="video in videos" :key="video.id" @click="selected=video;step=2"><div><video :src="video.media.download_url" muted preload="metadata"/><Play/></div><strong>{{video.caption||'SportUniverse video'}}</strong><small>{{video.counts.views}} views</small></button></div><div v-else class="promote-empty"><h3>No published videos</h3><p>Post a video before creating a promotion.</p><Link href="/upload">Upload video</Link></div></section>
<section v-else-if="step===2" class="promote-card"><h2>What is your goal?</h2><p>Choose the result you want.</p><div class="promote-options"><button v-for="item in goals" :class="{selected:goal===item.id}" @click="goal=item.id"><component :is="item.icon"/><span><strong>{{item.label}}</strong><small>{{item.hint}}</small></span><i><Check/></i></button></div><footer><button @click="step=1">Back</button><button class="primary" @click="step=3">Next<ChevronRight/></button></footer></section>
<section v-else-if="step===3" class="promote-card"><h2>Audience and budget</h2><div class="promote-segment"><button :class="{selected:audience==='automatic'}" @click="audience='automatic'">Automatic<small>Recommended</small></button><button :class="{selected:audience==='sports'}" @click="audience='sports'">Sports audience<small>Sports interests</small></button></div><label class="promote-range"><span>Daily budget <strong>{{money(budget)}}</strong></span><input v-model.number="budget" type="range" min="50" max="1000" step="50"/></label><label class="promote-days"><span>Duration</span><select v-model.number="days"><option v-for="n in [1,2,3,5,7,14]" :value="n">{{n}} day{{n>1?'s':''}}</option></select></label><div class="promote-estimate"><Sparkles/><div><small>Estimated reach</small><strong>{{reach[0].toLocaleString()}} – {{reach[1].toLocaleString()}}</strong><span>people over {{days}} days</span></div></div><footer><button @click="step=2">Back</button><button class="primary" @click="step=4">Review<ChevronRight/></button></footer></section>
<section v-else class="promote-card promote-review"><h2>Review promotion</h2><div class="review-post"><video :src="selected.media.download_url" muted/><div><strong>{{selected.caption||'SportUniverse video'}}</strong><small>{{goals.find(i=>i.id===goal)?.label}}</small></div></div><dl><div><dt>Audience</dt><dd>{{audience==='automatic'?'Automatic':'Sports audience'}}</dd></div><div><dt>Budget</dt><dd>{{money(budget)}} × {{days}} days</dd></div><div><dt>Estimated reach</dt><dd>{{reach[0].toLocaleString()}} – {{reach[1].toLocaleString()}}</dd></div><div class="total"><dt>Total</dt><dd>{{money(total)}}</dd></div></dl><p v-if="notice" class="promote-notice">{{notice}}</p><footer><button @click="step=3">Back</button><button class="primary" @click="save">Continue to payment</button></footer></section></main></AppShell></template>
