import { useState } from 'react';
import { ActivityIndicator, Alert, FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useInfiniteQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { api } from '../../src/api/client';
import { PrimaryButton } from '../../src/components/PrimaryButton';
import { ScreenMessage } from '../../src/components/ScreenMessage';
import { useAuthStore } from '../../src/stores/auth';
import { colors, radius, spacing } from '../../src/theme';
import type { AppNotification, PaginatedResponse } from '../../src/types/api';

const categories = [{ value: '', label: 'All' }, { value: 'unread', label: 'Unread' }, { value: 'messages', label: 'Messages' }, { value: 'opportunities', label: 'Opportunities' }, { value: 'followers', label: 'Followers' }, { value: 'engagement', label: 'Engagement' }];

export default function NotificationsScreen() {
  const user = useAuthStore(state => state.user); const [category, setCategory] = useState(''); const client = useQueryClient();
  const notifications = useInfiniteQuery({ queryKey: ['notifications', category], enabled: Boolean(user), initialPageParam: 1, queryFn: async ({ pageParam }) => (await api.get<PaginatedResponse<AppNotification>>('/notifications', { params: { page: pageParam, per_page: 30, unread: category === 'unread' ? 1 : undefined, category: category && category !== 'unread' ? category : undefined } })).data, getNextPageParam: page => page.meta.current_page < page.meta.last_page ? page.meta.current_page + 1 : undefined, refetchInterval: 15000 });
  const readAll = useMutation({ mutationFn: () => api.post('/notifications/read-all'), onSuccess: () => invalidate(client), onError: error => Alert.alert('Unable to update notifications', message(error)) });
  const items = notifications.data?.pages.flatMap(page => page.data) ?? [];
  if (!user) return <SafeAreaView style={styles.safe}><TopBar /><ScreenMessage icon="notifications-outline" title="Sign in for notifications" message="Activity from the SportUniverse community will appear here." /></SafeAreaView>;
  return <SafeAreaView edges={['top']} style={styles.safe}><TopBar settings /><FlatList data={items} keyExtractor={item => item.id} contentContainerStyle={styles.list} refreshControl={<RefreshControl refreshing={notifications.isRefetching && !notifications.isFetchingNextPage} onRefresh={() => notifications.refetch()} tintColor={colors.blue} />} ListHeaderComponent={<View><FlatList horizontal data={categories} keyExtractor={item => item.value || 'all'} showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters} renderItem={({ item }) => <Pressable onPress={() => setCategory(item.value)} style={[styles.filter, category === item.value && styles.filterActive]}><Text style={[styles.filterText, category === item.value && styles.filterTextActive]}>{item.label}</Text></Pressable>} /><View style={styles.summary}><Text style={styles.summaryText}>{notifications.data?.pages[0]?.meta.total ?? 0} notifications</Text><Pressable disabled={readAll.isPending} onPress={() => readAll.mutate()}><Text style={styles.readAll}>Mark all read</Text></Pressable></View></View>} renderItem={({ item }) => <NotificationRow item={item} />} ItemSeparatorComponent={() => <View style={{ height: 9 }} />} ListEmptyComponent={notifications.isLoading ? <ActivityIndicator style={styles.loader} color={colors.blue} /> : notifications.isError ? <ScreenMessage icon="cloud-offline-outline" title="Notifications unavailable" message="Check your connection and try again." action={<PrimaryButton label="Try again" secondary onPress={() => notifications.refetch()} />} /> : <ScreenMessage icon="notifications-outline" title="Nothing new yet" message="New activity will appear here." />} onEndReached={() => { if (notifications.hasNextPage && !notifications.isFetchingNextPage) notifications.fetchNextPage(); }} onEndReachedThreshold={.4} ListFooterComponent={notifications.isFetchingNextPage ? <ActivityIndicator style={{ margin: 20 }} color={colors.blue} /> : <View style={{ height: 24 }} />} /></SafeAreaView>;
}

function NotificationRow({ item }: { item: AppNotification }) {
  const client = useQueryClient(); const action = notificationAction(item);
  const read = useMutation({ mutationFn: () => api.patch(`/notifications/${item.id}/read`), onSuccess: () => { invalidate(client); action(); } });
  const remove = useMutation({ mutationFn: () => api.delete(`/notifications/${item.id}`), onSuccess: () => invalidate(client), onError: error => Alert.alert('Unable to delete notification', message(error)) });
  return <Pressable onPress={() => item.read_at ? action() : read.mutate()} style={({ pressed }) => [styles.card, !item.read_at && styles.cardUnread, pressed && { opacity: .75 }]}><View style={[styles.icon, { backgroundColor: iconColor(item.category).background }]}><Ionicons name={iconColor(item.category).icon} size={21} color={iconColor(item.category).color} /></View><View style={styles.copy}><Text style={styles.title}>{notificationTitle(item)}</Text><Text numberOfLines={2} style={styles.body}>{notificationBody(item)}</Text><Text style={styles.time}>{relativeTime(item.created_at)}</Text></View>{!item.read_at ? <View style={styles.dot} /> : null}<Pressable accessibilityLabel="Delete notification" hitSlop={10} disabled={remove.isPending} onPress={() => remove.mutate()}><Ionicons name="close" size={18} color={colors.muted} /></Pressable></Pressable>;
}

function TopBar({ settings }: { settings?: boolean }) { return <View style={styles.topBar}><Pressable accessibilityLabel="Go back" hitSlop={12} onPress={() => router.back()}><Ionicons name="arrow-back" size={24} color={colors.white} /></Pressable><Text style={styles.topTitle}>Notifications</Text>{settings ? <Pressable accessibilityLabel="Notification settings" hitSlop={12} onPress={() => router.push('/notifications/preferences')}><Ionicons name="settings-outline" size={22} color={colors.white} /></Pressable> : <View style={{ width: 24 }} />}</View>; }
function invalidate(client: ReturnType<typeof useQueryClient>) { client.invalidateQueries({ queryKey: ['notifications'] }); }
function notificationAction(item: AppNotification) { return () => { const data = item.data; if (data.conversation_id) router.push(`/conversation/${data.conversation_id}` as never); else if (data.opportunity_id) router.push(`/opportunity/${data.opportunity_id}` as never); else if (data.profile_slug || data.slug) router.push(`/profile/${data.profile_slug || data.slug}` as never); else router.push('/(tabs)/feed'); }; }
function notificationTitle(item: AppNotification) { const data = item.data; return data.title || data.actor_name || data.sender_name || ({ messages: 'New message', message_requests: 'Message request', opportunities: 'Opportunity update', followers: 'New follower', engagement: 'New engagement', moderation: 'Moderation update', profile_views: 'Profile activity' } as Record<string, string>)[item.category] || 'SportUniverse update'; }
function notificationBody(item: AppNotification) { const data = item.data; return data.preview || data.message || data.opportunity_title || (data.event === 'video_liked' ? 'Someone liked your post.' : data.event === 'new_follower' ? 'Someone started following you.' : 'You have new activity on SportUniverse.'); }
function iconColor(category: string): { icon: keyof typeof Ionicons.glyphMap; color: string; background: string } { if (category === 'messages' || category === 'message_requests') return { icon: 'chatbubble-outline', color: '#79A3FF', background: 'rgba(27,99,243,.15)' }; if (category === 'opportunities') return { icon: 'briefcase-outline', color: colors.orange, background: 'rgba(255,176,32,.13)' }; if (category === 'followers') return { icon: 'person-add-outline', color: '#69DDA4', background: 'rgba(24,178,107,.13)' }; if (category === 'engagement') return { icon: 'heart-outline', color: '#FF8FC7', background: 'rgba(230,70,162,.13)' }; return { icon: 'notifications-outline', color: '#79A3FF', background: 'rgba(27,99,243,.15)' }; }
function relativeTime(value: string) { const seconds = Math.max(1, Math.floor((Date.now() - new Date(value).getTime()) / 1000)); if (seconds < 60) return 'Just now'; if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`; if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`; if (seconds < 604800) return `${Math.floor(seconds / 86400)}d ago`; return new Date(value).toLocaleDateString(); }
function message(error: any) { return error?.response?.data?.message || 'Please try again.'; }

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.navy }, topBar: { height: 56, paddingHorizontal: spacing.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.line, backgroundColor: '#091725' }, topTitle: { color: colors.white, fontSize: 15, fontWeight: '900' }, list: { flexGrow: 1, paddingHorizontal: spacing.md }, filters: { gap: 8, paddingTop: 14, paddingBottom: 12 }, filter: { paddingHorizontal: 14, paddingVertical: 9, borderRadius: radius.pill, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface }, filterActive: { borderColor: colors.blue, backgroundColor: colors.blue }, filterText: { color: colors.muted, fontSize: 11, fontWeight: '800' }, filterTextActive: { color: '#fff' }, summary: { flexDirection: 'row', justifyContent: 'space-between', paddingBottom: 12 }, summaryText: { color: colors.muted, fontSize: 11 }, readAll: { color: '#79A3FF', fontSize: 11, fontWeight: '900' }, loader: { marginTop: 120 }, card: { minHeight: 88, flexDirection: 'row', alignItems: 'center', gap: 11, padding: 13, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface }, cardUnread: { borderColor: 'rgba(27,99,243,.45)', backgroundColor: '#162B45' }, icon: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' }, copy: { flex: 1, minWidth: 0 }, title: { color: colors.white, fontSize: 13, fontWeight: '900' }, body: { color: '#C6D3E1', fontSize: 12, lineHeight: 17, marginTop: 3 }, time: { color: colors.muted, fontSize: 9, marginTop: 5 }, dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.blue } });
