import { ActivityIndicator, FlatList, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { api } from '../../src/api/client';
import { ScreenMessage } from '../../src/components/ScreenMessage';
import { colors, radius, spacing } from '../../src/theme';
import type { Profile } from '../../src/types/api';
import { absoluteMediaUrl } from '../../src/utils/url';

type WomenData = {
  profiles: Profile[];
  videos: { id: string; caption?: string | null; creator: { name: string; slug?: string | null }; sport?: string | null; views: number }[];
  opportunities: { id: string; title: string; type: string; poster: string; sport?: string | null; city?: string | null; is_remote: boolean; deadline?: string | null }[];
  sports: { id: number; name: string; slug: string; athlete_profiles_count: number }[];
};

export default function WomenInSportsScreen() {
  const [sportId, setSportId] = useState<number>();
  const page = useQuery({ queryKey: ['women-in-sports', sportId], queryFn: async () => (await api.get<{ data: WomenData; stats: { profiles: number; videos: number; opportunities: number } }>('/women-in-sports', { params: { sport_id: sportId } })).data });
  const data = page.data?.data;
  const stats = page.data?.stats;
  return <SafeAreaView edges={['top']} style={styles.safe}><View style={styles.header}><Pressable accessibilityLabel="Go back" onPress={() => router.back()}><Ionicons name="chevron-back" size={26} color="#fff" /></Pressable><Text style={styles.headerTitle}>Women in Sports</Text><Ionicons name="female" size={23} color={colors.pink} /></View>{page.isLoading ? <ActivityIndicator style={{ flex: 1 }} color={colors.pink} /> : page.isError || !data || !stats ? <ScreenMessage icon="cloud-offline-outline" title="Page unavailable" message="Check your connection and try again." /> : <ScrollView contentContainerStyle={styles.content}><View style={styles.hero}><Text style={styles.eyebrow}>CELEBRATE · DISCOVER · SUPPORT</Text><Text style={styles.title}>Women changing the game.</Text><Text style={styles.subtitle}>Discover athletes and professionals, watch their work and find inclusive opportunities.</Text><View style={styles.stats}><Stat value={stats.profiles} label="Profiles" /><Stat value={stats.videos} label="Highlights" /><Stat value={stats.opportunities} label="Opportunities" /></View></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}><Filter label="All sports" active={!sportId} onPress={() => setSportId(undefined)} />{data.sports.map(sport => <Filter key={sport.id} label={sport.name} active={sportId === sport.id} onPress={() => setSportId(sport.id)} />)}</ScrollView><Section title="Featured profiles">{data.profiles.length ? data.profiles.map(profile => <ProfileRow key={profile.id} item={profile} />) : <Empty text="No profiles for this sport yet." />}</Section><Section title="Opportunities">{data.opportunities.length ? data.opportunities.map(item => <Pressable key={item.id} onPress={() => router.push(`/opportunity/${item.id}` as never)} style={styles.opportunity}><View style={styles.opportunityIcon}><Ionicons name="briefcase-outline" size={21} color={colors.orange} /></View><View style={styles.rowCopy}><Text style={styles.name}>{item.title}</Text><Text style={styles.detail}>{[item.sport, item.is_remote ? 'Remote' : item.city, item.poster].filter(Boolean).join(' · ')}</Text></View><Ionicons name="chevron-forward" size={19} color={colors.muted} /></Pressable>) : <Empty text="No matching opportunities right now." />}</Section><Section title="Recent highlights">{data.videos.length ? data.videos.map(item => <Pressable key={item.id} onPress={() => router.push(`/post/${item.id}` as never)} style={styles.highlight}><Ionicons name="play-circle-outline" size={30} color={colors.pink} /><View style={styles.rowCopy}><Text numberOfLines={2} style={styles.name}>{item.caption || 'Sports highlight'}</Text><Text style={styles.detail}>{item.creator.name} · {item.sport || 'Sport'} · {item.views} views</Text></View><Ionicons name="chevron-forward" size={18} color={colors.muted} /></Pressable>) : <Empty text="New highlights will appear here." />}</Section></ScrollView>}</SafeAreaView>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text><View style={styles.sectionList}>{children}</View></View>; }
function Stat({ value, label }: { value: number; label: string }) { return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
function Filter({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={[styles.filter, active && styles.filterActive]}><Text style={[styles.filterText, active && styles.filterTextActive]}>{label}</Text></Pressable>; }
function Empty({ text }: { text: string }) { return <Text style={styles.empty}>{text}</Text>; }
function ProfileRow({ item }: { item: Profile }) { const photo = absoluteMediaUrl(item.images.profile); const initials = item.name.split(/\s+/).slice(0, 2).map(part => part[0]).join('').toUpperCase(); return <Pressable onPress={() => router.push(`/profile/${item.slug}` as never)} style={styles.row}>{photo ? <Image source={{ uri: photo }} style={styles.avatar} /> : <View style={[styles.avatar, styles.fallback]}><Text style={styles.initials}>{initials}</Text></View>}<View style={styles.rowCopy}><Text style={styles.name}>{item.name}</Text><Text style={styles.detail}>{[item.athlete?.sport?.name || item.roles[0], item.athlete?.position?.name, item.location.city].filter(Boolean).join(' · ')}</Text></View><Ionicons name="chevron-forward" size={19} color={colors.muted} /></Pressable>; }

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.navy }, header: { height: 56, paddingHorizontal: spacing.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.line }, headerTitle: { color: '#fff', fontSize: 17, fontWeight: '900' }, content: { paddingBottom: 50 }, hero: { padding: spacing.lg, backgroundColor: 'rgba(185,107,157,.1)' }, eyebrow: { color: '#FF8FC7', fontSize: 10, fontWeight: '900', letterSpacing: .8 }, title: { color: '#fff', fontSize: 29, lineHeight: 34, fontWeight: '900', marginTop: 8 }, subtitle: { color: '#C9D5E3', fontSize: 13, lineHeight: 20, marginTop: 9 }, stats: { flexDirection: 'row', gap: 9, marginTop: 20 }, stat: { flex: 1, padding: 12, borderRadius: radius.md, backgroundColor: 'rgba(255,255,255,.06)' }, statValue: { color: '#fff', fontSize: 19, fontWeight: '900' }, statLabel: { color: colors.muted, fontSize: 9, marginTop: 3 }, filters: { gap: 8, padding: spacing.md }, filter: { paddingHorizontal: 14, paddingVertical: 9, borderRadius: radius.pill, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface }, filterActive: { borderColor: colors.pink, backgroundColor: colors.pink }, filterText: { color: colors.muted, fontSize: 11, fontWeight: '800' }, filterTextActive: { color: '#fff' },
  section: { paddingHorizontal: spacing.md, marginTop: 16 }, sectionTitle: { color: '#fff', fontSize: 18, fontWeight: '900', marginBottom: 10 }, sectionList: { gap: 9 }, row: { minHeight: 78, padding: 11, flexDirection: 'row', alignItems: 'center', gap: 11, borderRadius: radius.lg, backgroundColor: colors.surface }, avatar: { width: 56, height: 56, borderRadius: 28 }, fallback: { alignItems: 'center', justifyContent: 'center', backgroundColor: colors.pink }, initials: { color: '#fff', fontWeight: '900' }, rowCopy: { flex: 1 }, name: { color: '#fff', fontSize: 13, fontWeight: '900' }, detail: { color: colors.muted, fontSize: 10, lineHeight: 15, marginTop: 4 }, opportunity: { minHeight: 72, padding: 11, flexDirection: 'row', alignItems: 'center', gap: 11, borderRadius: radius.lg, backgroundColor: colors.surface }, opportunityIcon: { width: 43, height: 43, borderRadius: 22, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,176,32,.12)' }, highlight: { minHeight: 70, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 11, borderRadius: radius.md, backgroundColor: colors.surface }, empty: { color: colors.muted, textAlign: 'center', padding: 24 },
});
