import { useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { BrandMark } from '../../src/components/BrandMark';
import { PrimaryButton } from '../../src/components/PrimaryButton';
import { useAuthStore } from '../../src/stores/auth';
import { colors, radius, spacing } from '../../src/theme';

export default function LoginScreen(){const [login,setLogin]=useState('');const [password,setPassword]=useState('');const {busy,error,login:signIn,clearError}=useAuthStore();const submit=async()=>{if(await signIn({login,password}))router.replace('/(tabs)/feed');};return <SafeAreaView style={styles.safe}><KeyboardAvoidingView style={styles.page} behavior={Platform.OS==='ios'?'padding':undefined}><View style={styles.top}><Pressable onPress={()=>router.back()}><Ionicons name="arrow-back" size={24} color="#fff"/></Pressable><BrandMark/></View><View style={styles.content}><Text style={styles.eyebrow}>WELCOME BACK</Text><Text style={styles.title}>Your sports world starts here.</Text><Text style={styles.copy}>Sign in to keep scrolling, follow athletes and unlock opportunities.</Text><Text style={styles.label}>Email address or phone</Text><TextInput value={login} onChangeText={v=>{setLogin(v);clearError();}} autoCapitalize="none" keyboardType="email-address" style={styles.input} placeholder="name@example.com" placeholderTextColor="#6F8298"/><Text style={styles.label}>Password</Text><TextInput value={password} onChangeText={v=>{setPassword(v);clearError();}} secureTextEntry style={styles.input} placeholder="Enter your password" placeholderTextColor="#6F8298"/>{error&&<Text style={styles.error}>{error}</Text>}<PrimaryButton label="Sign in" loading={busy} onPress={submit} style={{marginTop:18}}/><Text style={styles.footer}>New to SportUniverse? <Text style={styles.link} onPress={()=>router.replace('/(auth)/register')}>Create an account</Text></Text></View></KeyboardAvoidingView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.navy},page:{flex:1,padding:spacing.lg},top:{flexDirection:'row',alignItems:'center',gap:20},content:{flex:1,justifyContent:'center'},eyebrow:{color:'#79A3FF',fontSize:12,fontWeight:'900',letterSpacing:1},title:{color:colors.white,fontSize:38,lineHeight:40,fontWeight:'900',letterSpacing:-1.6,marginTop:10},copy:{color:colors.muted,fontSize:15,lineHeight:22,marginTop:12,marginBottom:28},label:{color:'#DCE7F5',fontSize:12,fontWeight:'800',marginBottom:7,marginTop:13},input:{height:52,borderRadius:radius.md,borderWidth:1,borderColor:colors.line,backgroundColor:'rgba(255,255,255,.055)',paddingHorizontal:16,color:'#fff',fontSize:15},error:{color:'#FF8FBF',fontSize:12,marginTop:10},footer:{color:colors.muted,textAlign:'center',marginTop:22},link:{color:'#79A3FF',fontWeight:'800'}});
