import { useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { BrandMark } from '../../src/components/BrandMark';
import { PrimaryButton } from '../../src/components/PrimaryButton';
import { useAuthStore } from '../../src/stores/auth';
import { colors, radius, spacing } from '../../src/theme';

const roles=[['athlete','Athlete','football'],['fan','Fan','heart'],['coach','Coach','shield-checkmark'],['scout','Scout / Agent','search'],['club','Club / Academy','business'],['business','Business / Sponsor','briefcase']];
export default function RegisterScreen(){const [step,setStep]=useState(1);const [form,setForm]=useState({name:'',email:'',phone:'',password:'',password_confirmation:'',role:''});const {busy,error,register,clearError}=useAuthStore();const update=(key:string,value:string)=>{setForm({...form,[key]:value});clearError();};const submit=async()=>{if(await register(form))router.replace('/(tabs)/feed');};return <SafeAreaView style={styles.safe}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={styles.page} keyboardShouldPersistTaps="handled"><View style={styles.top}><Pressable onPress={()=>step===2?setStep(1):router.back()}><Ionicons name="arrow-back" size={24} color="#fff"/></Pressable><BrandMark/></View><View style={styles.steps}><View style={styles.stepActive}/><View style={step===2?styles.stepActive:styles.step}/></View><Text style={styles.eyebrow}>CREATE YOUR PROFILE</Text><Text style={styles.title}>{step===1?'Join the universe.':'How do you play?'}</Text>{step===1?<View><Field label="Full name" value={form.name} onChangeText={(v:string)=>update('name',v)} placeholder="Your full name"/><Field label="Email address" value={form.email} onChangeText={(v:string)=>update('email',v)} placeholder="name@example.com" autoCapitalize="none"/><Field label="Phone (optional)" value={form.phone} onChangeText={(v:string)=>update('phone',v)} placeholder="+27"/><Field label="Password" value={form.password} onChangeText={(v:string)=>update('password',v)} placeholder="8+ characters" secureTextEntry/><Field label="Confirm password" value={form.password_confirmation} onChangeText={(v:string)=>update('password_confirmation',v)} placeholder="Repeat password" secureTextEntry/><PrimaryButton label="Choose your role" onPress={()=>setStep(2)} style={{marginTop:20}}/></View>:<View><Text style={styles.copy}>Choose the role that best describes you. You can complete your profile later.</Text><View style={styles.roleGrid}>{roles.map(([value,label,icon])=><Pressable key={value} onPress={()=>update('role',value)} style={[styles.role,form.role===value&&styles.roleSelected]}><Ionicons name={icon as any} size={22} color={form.role===value?'#fff':'#79A3FF'}/><Text style={styles.roleText}>{label}</Text></Pressable>)}</View>{error&&<Text style={styles.error}>{error}</Text>}<PrimaryButton label="Enter SportUniverse" loading={busy} onPress={submit} style={{marginTop:20}}/></View>}<Text style={styles.footer}>Already a member? <Text style={styles.link} onPress={()=>router.replace('/(auth)/login')}>Sign in</Text></Text></ScrollView></KeyboardAvoidingView></SafeAreaView>}
function Field(props:any){return <View><Text style={styles.label}>{props.label}</Text><TextInput {...props} style={styles.input} placeholderTextColor="#6F8298"/></View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.navy},page:{padding:spacing.lg,paddingBottom:40},top:{flexDirection:'row',alignItems:'center',gap:20},steps:{flexDirection:'row',gap:7,marginTop:30,marginBottom:25},step:{height:4,flex:1,borderRadius:4,backgroundColor:'rgba(255,255,255,.1)'},stepActive:{height:4,flex:1,borderRadius:4,backgroundColor:colors.blue},eyebrow:{color:'#79A3FF',fontSize:12,fontWeight:'900',letterSpacing:1},title:{color:colors.white,fontSize:38,lineHeight:40,fontWeight:'900',letterSpacing:-1.6,marginTop:9,marginBottom:16},copy:{color:colors.muted,lineHeight:21,marginBottom:15},label:{color:'#DCE7F5',fontSize:12,fontWeight:'800',marginBottom:7,marginTop:13},input:{height:50,borderRadius:radius.md,borderWidth:1,borderColor:colors.line,backgroundColor:'rgba(255,255,255,.055)',paddingHorizontal:16,color:'#fff'},roleGrid:{flexDirection:'row',flexWrap:'wrap',gap:10},role:{width:'48%',minHeight:94,padding:14,borderRadius:radius.md,borderWidth:1,borderColor:colors.line,backgroundColor:'rgba(255,255,255,.04)',justifyContent:'space-between'},roleSelected:{borderColor:colors.blue,backgroundColor:'rgba(27,99,243,.18)'},roleText:{color:colors.white,fontWeight:'800',fontSize:13},error:{color:'#FF8FBF',fontSize:12,marginTop:12},footer:{color:colors.muted,textAlign:'center',marginTop:22},link:{color:'#79A3FF',fontWeight:'800'}});
