import { useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { api } from '../../src/api/client';
import { BrandMark } from '../../src/components/BrandMark';
import { PrimaryButton } from '../../src/components/PrimaryButton';
import { colors, radius, spacing } from '../../src/theme';

export default function ResetPasswordScreen() {
  const params = useLocalSearchParams<{ token?: string; email?: string }>();
  const [email, setEmail] = useState(params.email ?? ''); const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [visible, setVisible] = useState(false); const [busy, setBusy] = useState(false);
  const submit = async () => { if (!params.token) return Alert.alert('Reset link invalid', 'Request a new password reset link.'); if (password.length < 8 || password !== confirmation) return Alert.alert('Check your password', password.length < 8 ? 'Use at least eight characters.' : 'The password confirmation does not match.'); setBusy(true); try { const response = await api.post('/auth/reset-password', { token: params.token, email: email.trim(), password, password_confirmation: confirmation }); Alert.alert('Password reset', response.data.message, [{ text: 'Sign in', onPress: () => router.replace('/(auth)/login') }]); } catch (error: any) { Alert.alert('Password not reset', error?.response?.data?.message || Object.values(error?.response?.data?.errors || {}).flat()[0] as string || 'The link may have expired. Request a new one.'); } finally { setBusy(false); } };
  return <SafeAreaView style={styles.safe}><KeyboardAvoidingView style={styles.page} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={styles.top}><Pressable accessibilityLabel="Go back" onPress={() => router.back()}><Ionicons name="arrow-back" size={24} color="#fff" /></Pressable><BrandMark /></View><View style={styles.content}><Text style={styles.title}>Choose a new password.</Text><Text style={styles.copy}>Use at least eight characters and avoid passwords you use elsewhere.</Text><Field label="Email address" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" /><View><Field label="New password" value={password} onChangeText={setPassword} secureTextEntry={!visible} /><Pressable accessibilityLabel={visible ? 'Hide passwords' : 'Show passwords'} onPress={() => setVisible(value => !value)} style={styles.eye}><Ionicons name={visible ? 'eye-off-outline' : 'eye-outline'} size={20} color={colors.muted} /></Pressable></View><Field label="Confirm password" value={confirmation} onChangeText={setConfirmation} secureTextEntry={!visible} /><PrimaryButton label="Reset password" loading={busy} disabled={!email.trim() || !password || !confirmation} onPress={submit} style={{ marginTop: 20 }} /><Pressable onPress={() => router.replace('/(auth)/forgot-password')} style={styles.newLink}><Text style={styles.newLinkText}>Request a new reset link</Text></Pressable></View></KeyboardAvoidingView></SafeAreaView>;
}
function Field({ label, ...props }: { label: string } & React.ComponentProps<typeof TextInput>) { return <View style={{ marginTop: 15 }}><Text style={styles.label}>{label}</Text><TextInput {...props} placeholderTextColor="#71849B" style={styles.input} /></View>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.navy }, page: { flex: 1, padding: spacing.lg }, top: { flexDirection: 'row', alignItems: 'center', gap: 20 }, content: { flex: 1, justifyContent: 'center' }, title: { color: '#fff', fontSize: 32, lineHeight: 37, fontWeight: '900', letterSpacing: -1 }, copy: { color: colors.muted, fontSize: 13, lineHeight: 20, marginTop: 9, marginBottom: 10 }, label: { color: '#DCE7F5', fontSize: 11, fontWeight: '800', marginBottom: 7 }, input: { height: 52, paddingHorizontal: 15, paddingRight: 46, color: '#fff', borderRadius: radius.md, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface }, eye: { position: 'absolute', right: 13, bottom: 15 }, newLink: { minHeight: 44, alignItems: 'center', justifyContent: 'center', marginTop: 8 }, newLinkText: { color: '#79A3FF', fontSize: 12, fontWeight: '800' } });
