<script setup lang="ts">
import { Head, Link } from '@inertiajs/vue3';
import { Bell, CheckCheck, Heart, MessageCircle, Tag, Trash2, UserPlus } from '@lucide/vue';
import { computed, onMounted, onUnmounted, ref } from 'vue';
import AppShell from '../../Layouts/AppShell.vue';

const tabs = [{ key:'all', label:'All activity' },{ key:'likes', label:'Likes' },{ key:'comments', label:'Comments' },{ key:'mentions', label:'Mentions and tags' },{ key:'followers', label:'Followers' },{ key:'messages', label:'Messages' },{ key:'opportunities', label:'Opportunities' }];
const active = ref('all'); const notifications = ref<any[]>([]); const loading = ref(true); const busy = ref(''); const followed = ref(new Set<number>());
const csrf = () => (document.querySelector('meta[name="csrf-token"]') as HTMLMetaElement)?.content ?? '';
const filtered = computed(() => notifications.value.filter(item => active.value === 'all' || active.value === 'likes' ? active.value !== 'likes' || item.data?.event === 'video_liked' : active.value === 'comments' ? item.data?.event === 'video_commented' : active.value === 'mentions' ? ['mentioned','tagged'].includes(item.data?.event) : item.category === active.value));
const groups = computed(() => { const result: Record<string,any[]> = {}; filtered.value.forEach(item => { const date = new Date(item.created_at); const now = new Date(); const yesterday = new Date(); yesterday.setDate(now.getDate()-1); const label = date.toDateString() === now.toDateString() ? 'Today' : date.toDateString() === yesterday.toDateString() ? 'Yesterday' : date.getMonth() === now.getMonth() && date.getFullYear() === now.getFullYear() ? 'This Month' : 'Previous'; (result[label] ??= []).push(item); }); return result; });
const initials = (name='SU') => name.split(/\s+/).map(part => part[0]).join('').slice(0,2).toUpperCase();
const ago = (value:string) => { const seconds=Math.floor((Date.now()-+new Date(value))/1000); if(seconds<60)return 'now'; if(seconds<3600)return `${Math.floor(seconds/60)}m`; if(seconds<86400)return `${Math.floor(seconds/3600)}h`; return new Date(value).toLocaleDateString(undefined,{month:'short',day:'numeric'}); };
const text = (item:any) => ({ video_liked:'liked your video', video_commented:'commented on your video', new_follower:'started following you', new_message:'sent you a message', message_request_received:'sent you a message request', message_request_accepted:'accepted your message request', opportunity_application_status:`updated your application${item.data?.status ? ` to ${item.data.status}` : ''}`, media_moderated:'updated your media status' }[item.data?.event] ?? 'sent you a notification');
const icon = (item:any) => item.data?.event === 'video_liked' ? Heart : item.data?.event === 'video_commented' || item.category === 'messages' ? MessageCircle : item.category === 'followers' ? UserPlus : item.data?.event?.includes('mention') ? Tag : Bell;
const href = (item:any) => item.category === 'messages' || item.category === 'message_requests' ? '/messages' : item.category === 'opportunities' ? '/applications' : item.data?.video_id ? `/feed#${item.data.video_id}` : '/feed';
const load = async () => { const response=await fetch('/api/v1/notifications?per_page=100',{credentials:'same-origin',headers:{Accept:'application/json'}}); notifications.value=(await response.json()).data??[]; loading.value=false; };
const markRead = async (item:any) => { if(item.read_at)return; await fetch(`/api/v1/notifications/${item.id}/read`,{method:'PATCH',credentials:'same-origin',headers:{Accept:'application/json','X-CSRF-TOKEN':csrf()}}); item.read_at=new Date().toISOString(); };
const readAll = async () => { await fetch('/api/v1/notifications/read-all',{method:'POST',credentials:'same-origin',headers:{Accept:'application/json','X-CSRF-TOKEN':csrf()}}); notifications.value.forEach(item=>item.read_at??=new Date().toISOString()); };
const remove = async (item:any) => { await fetch(`/api/v1/notifications/${item.id}`,{method:'DELETE',credentials:'same-origin',headers:{Accept:'application/json','X-CSRF-TOKEN':csrf()}}); notifications.value=notifications.value.filter(n=>n.id!==item.id); };
const followBack = async (item:any) => { const id=item.data?.actor_id;if(!id)return;busy.value=String(id);const response=await fetch(`/athletes/${id}/follow`,{method:'POST',credentials:'same-origin',headers:{Accept:'application/json','X-CSRF-TOKEN':csrf()}});if(response.ok)followed.value=new Set([...followed.value,id]);busy.value=''; };
const realtime=(event:Event)=>{const data=(event as CustomEvent<any>).detail;notifications.value.unshift({id:data.id??crypto.randomUUID(),category:data.category??'all',data,read_at:null,created_at:new Date().toISOString()})};
onMounted(()=>{load();window.addEventListener('sportuniverse:notification',realtime)});onUnmounted(()=>window.removeEventListener('sportuniverse:notification',realtime));
</script>
<template><Head title="Notifications"/><AppShell><main class="notifications-page"><header class="notifications-heading"><div><h1>Notifications</h1><p>Stay up to date with activity across SportUniverse.</p></div><button @click="readAll"><CheckCheck :size="16"/> Mark all as read</button></header><nav class="notification-tabs"><button v-for="tab in tabs" :key="tab.key" :class="{active:active===tab.key}" @click="active=tab.key">{{tab.label}}</button></nav><p v-if="loading" class="notifications-empty">Loading notifications…</p><section v-else-if="filtered.length" class="notification-groups"><div v-for="(items,label) in groups" :key="label" class="notification-group"><h2>{{label}}</h2><article v-for="item in items" :key="item.id" class="notification-row" :class="{unread:!item.read_at}" @click="markRead(item)"><span class="notification-avatar">{{initials(item.data?.actor_name||item.data?.sender_name)}}<component :is="icon(item)"/></span><div class="notification-copy"><strong>{{item.data?.actor_name||item.data?.sender_name||'SportUniverse'}}</strong><p>{{text(item)}} <span>· {{ago(item.created_at)}}</span></p><small v-if="item.data?.preview">{{item.data.preview}}</small></div><div class="notification-actions"><button v-if="item.category==='followers' && item.data?.actor_id && !followed.has(item.data.actor_id)" class="follow-back" :disabled="busy===String(item.data.actor_id)" @click.stop="followBack(item)">{{busy===String(item.data.actor_id)?'Following…':'Follow back'}}</button><span v-else-if="item.category==='followers' && followed.has(item.data.actor_id)" class="friends">Following</span><Link v-else :href="href(item)" @click.stop>View</Link><button class="delete-notification" aria-label="Delete" @click.stop="remove(item)"><Trash2 :size="15"/></button></div></article></div></section><section v-else class="notifications-empty"><Bell :size="36"/><h2>No notifications here</h2><p>New activity will appear in this tab.</p></section></main></AppShell></template>
