<script setup lang="ts">
import { Head, Link } from '@inertiajs/vue3';
import { Building2, ClipboardList, GitCompareArrows, NotebookPen, Search, Send, UserPlus } from '@lucide/vue';
import { computed, onMounted, ref } from 'vue';
import AppShell from '../../Layouts/AppShell.vue';
const data=ref<any>(),pipeline=ref<any[]>([]),results=ref<any[]>([]),chosen=ref<any[]>([]),comparison=ref<any[]>([]),tab=ref('shortlists'),busy=ref(false),notice=ref(''),error=ref(''),query=ref(''),listName=ref(''),activeList=ref<number>(),note=ref(''),rating=ref(7),inviteTitle=ref('Trial invitation'),inviteMessage=ref(''),staffEmail=ref(''),staffRole=ref('scout'),club=ref<any>({});
const csrf=()=>(document.querySelector('meta[name="csrf-token"]') as HTMLMetaElement)?.content??'';
async function api(url:string,options:RequestInit={}){const response=await fetch(url,{...options,credentials:'same-origin',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':csrf()}});const payload=await response.json();if(!response.ok)throw new Error(payload.message??Object.values(payload.errors??{}).flat().join(' ')??'Request failed');return payload}
async function act(fn:()=>Promise<void>){busy.value=true;error.value='';notice.value='';try{await fn()}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function load(){await act(async()=>{data.value=(await api('/api/v1/club-tools')).data;pipeline.value=(await api('/api/v1/club-tools/pipeline')).data;club.value={name:data.value.workspace.name,bio:data.value.workspace.bio??'',website:data.value.workspace.website??''}})}
const search=()=>act(async()=>{results.value=(await api(`/api/v1/search/profiles?q=${encodeURIComponent(query.value)}&role=athlete&per_page=12`)).data??[]});
const createList=()=>act(async()=>{await api('/api/v1/club-tools/shortlists',{method:'POST',body:JSON.stringify({name:listName.value})});listName.value='';await load()});
const shortlist=(a:any)=>act(async()=>{if(!activeList.value)throw new Error('Select a shortlist first.');await api(`/api/v1/club-tools/shortlists/${activeList.value}/athletes`,{method:'POST',body:JSON.stringify({athlete_id:a.id})});notice.value=`${a.name} shortlisted.`;await load()});
function toggle(a:any){const i=chosen.value.findIndex(x=>x.id===a.id);i>=0?chosen.value.splice(i,1):chosen.value.length<4&&chosen.value.push(a)}
const compare=()=>act(async()=>{comparison.value=(await api('/api/v1/club-tools/compare',{method:'POST',body:JSON.stringify({athlete_ids:chosen.value.map(x=>x.id)})})).data;tab.value='compare'});
const saveNote=(a:any)=>act(async()=>{await api('/api/v1/club-tools/notes',{method:'POST',body:JSON.stringify({athlete_id:a.id,note:note.value,rating:rating.value})});note.value='';notice.value='Private scouting note saved.'});
const invite=(a:any)=>act(async()=>{await api('/api/v1/club-tools/invitations',{method:'POST',body:JSON.stringify({athlete_id:a.id,title:inviteTitle.value,message:inviteMessage.value})});inviteMessage.value='';notice.value='Trial invitation sent.';await load()});
const addStaff=()=>act(async()=>{await api('/api/v1/club-tools/staff',{method:'POST',body:JSON.stringify({email:staffEmail.value,role:staffRole.value})});staffEmail.value='';await load()});
const saveClub=()=>act(async()=>{await api('/api/v1/club-tools',{method:'PATCH',body:JSON.stringify(club.value)});notice.value='Club page updated.';await load()});
const move=(item:any,status:string)=>act(async()=>{await api(`/api/v1/club-tools/pipeline/${item.id}`,{method:'PATCH',body:JSON.stringify({status})});item.status=status;notice.value='Pipeline updated.'});
const athletes=computed(()=>data.value?.shortlists?.flatMap((x:any)=>x.athletes)??[]);onMounted(load);
</script>
<template><Head title="Club & Scout Tools"/><AppShell><main class="club"><header class="hero"><div><small>CLUB & SCOUT TOOLS</small><h1>{{ data?.workspace?.name||'Talent workspace' }}</h1><p>Discover, assess and move talent from first look to trial.</p></div><Building2 :size="44"/></header><p v-if="error" class="alert err">{{ error }}</p><p v-if="notice" class="alert ok">{{ notice }}</p><div class="metrics"><article><b>{{ data?.counts?.athletes??0 }}</b><span>Shortlisted</span></article><article><b>{{ data?.counts?.notes??0 }}</b><span>Private notes</span></article><article><b>{{ data?.counts?.invitations??0 }}</b><span>Invitations</span></article></div>
<nav><button v-for="x in [['shortlists','Shortlists'],['compare','Compare'],['pipeline','Pipeline'],['invitations','Invitations'],['staff','Staff'],['page','Club page']]" :class="{active:tab===x[0]}" @click="tab=x[0]">{{ x[1] }}</button></nav>
<section v-if="tab==='shortlists'" class="grid"><div class="card"><h2><ClipboardList/>Talent shortlists</h2><form class="inline" @submit.prevent="createList"><input v-model="listName" class="su-input" required placeholder="e.g. U21 midfielders"/><button class="su-btn su-btn-primary">Create</button></form><button v-for="list in data?.shortlists" class="list" :class="{selected:activeList===list.id}" @click="activeList=list.id"><span><b>{{ list.name }}</b><small>{{ list.athletes.length }} athletes</small></span></button></div><div class="card"><h2><Search/>Find athletes</h2><form class="inline" @submit.prevent="search"><input v-model="query" class="su-input" placeholder="Name, sport, position or city"/><button class="su-btn su-btn-primary">Search</button></form><article v-for="a in results" class="row"><span><Link :href="`/@${a.slug}`"><b>{{ a.name }}</b></Link><small>{{ [a.athlete?.sport?.name,a.athlete?.position?.name,a.location?.city].filter(Boolean).join(' · ') }}</small></span><button @click="shortlist(a)">Shortlist</button><button :class="{picked:chosen.some(x=>x.id===a.id)}" @click="toggle(a)">Compare</button></article><button v-if="chosen.length>=2" class="su-btn su-btn-primary" @click="compare">Compare {{ chosen.length }} athletes</button></div></section>
<section v-if="tab==='compare'" class="card"><h2><GitCompareArrows/>Athlete comparison</h2><p v-if="!comparison.length">Choose two to four athletes in Shortlists.</p><div v-for="key in ['name','sport','position','age','city','level','height','weight','followers','views']" class="compare"><b>{{ key }}</b><span v-for="a in comparison">{{ a[key]??'—' }}</span></div></section>
<section v-if="tab==='pipeline'" class="card"><h2><ClipboardList/>Application pipeline</h2><article v-for="item in pipeline" class="row"><span><b>{{ item.athlete.name }}</b><small>{{ item.opportunity }}</small></span><select :value="item.status" @change="move(item,($event.target as HTMLSelectElement).value)"><option v-for="s in ['submitted','reviewing','shortlisted','accepted','rejected']">{{ s }}</option></select></article><p v-if="!pipeline.length">Applications to your opportunities will appear here.</p></section>
<section v-if="tab==='invitations'" class="grid"><div class="card form"><h2><Send/>Send trial invitation</h2><select v-model="chosen[0]" class="su-input"><option :value="undefined">Select athlete</option><option v-for="a in athletes" :value="a">{{ a.name }}</option></select><input v-model="inviteTitle" class="su-input"/><textarea v-model="inviteMessage" class="su-input" placeholder="Date, venue and instructions"/><button class="su-btn su-btn-primary" :disabled="!chosen[0]||!inviteMessage" @click="invite(chosen[0])">Send invitation</button></div><div class="card"><h2>Sent invitations</h2><article v-for="x in data?.invitations" class="row"><span><b>{{ x.athlete_name }}</b><small>{{ x.title }}</small></span><b>{{ x.status }}</b></article></div></section>
<section v-if="tab==='staff'" class="grid"><div class="card form"><h2><UserPlus/>Add staff account</h2><input v-model="staffEmail" class="su-input" type="email" placeholder="Existing member email"/><select v-model="staffRole" class="su-input"><option v-for="r in ['manager','scout','coach','analyst']">{{ r }}</option></select><button class="su-btn su-btn-primary" @click="addStaff">Add staff</button></div><div class="card"><h2>Workspace staff</h2><article v-for="x in data?.staff" class="row"><span><b>{{ x.name }}</b><small>{{ x.email }}</small></span><b>{{ x.role }}</b></article></div></section>
<section v-if="tab==='page'" class="card form"><h2><Building2/>Club page</h2><label>Club name<input v-model="club.name" class="su-input"/></label><label>Website<input v-model="club.website" class="su-input" type="url"/></label><label>About<textarea v-model="club.bio" class="su-input"/></label><button class="su-btn su-btn-primary" @click="saveClub">Save page</button></section>
<section v-if="tab==='shortlists'&&athletes.length" class="card note"><h2><NotebookPen/>Private scouting note</h2><select v-model="chosen[0]" class="su-input"><option :value="undefined">Select athlete</option><option v-for="a in athletes" :value="a">{{ a.name }}</option></select><input v-model.number="rating" type="number" min="1" max="10" class="su-input"/><textarea v-model="note" class="su-input" placeholder="Visible only to club staff"/><button class="su-btn su-btn-primary" :disabled="!chosen[0]||!note" @click="saveNote(chosen[0])">Save note</button></section></main></AppShell></template>
<style scoped>.club{max-width:1250px;margin:auto;padding:32px}.hero{display:flex;justify-content:space-between;align-items:center;padding:30px;border-radius:24px;background:linear-gradient(135deg,#091c30,#174875);color:#fff}.hero h1{font-size:clamp(28px,4vw,46px);margin:7px 0}.hero small{color:#54d8ff;font-weight:800}.hero p{color:#c8d8e8}.metrics,.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:18px 0}.metrics article,.card{background:white;border:1px solid #dce4ed;border-radius:18px;padding:20px}.metrics b{display:block;font-size:28px}.metrics span,small{display:block;color:#718096}nav{display:flex;gap:8px;overflow:auto;margin:20px 0}nav button,.row button{border:0;border-radius:999px;padding:10px 16px;background:#e8eef5;white-space:nowrap;font-weight:700}nav .active,.row .picked{background:#1769ed;color:white}.grid{grid-template-columns:1fr 2fr}.card h2{display:flex;gap:8px;align-items:center}.inline,.row{display:flex;align-items:center;gap:10px}.inline{margin-bottom:12px}.row{justify-content:space-between;border-bottom:1px solid #e5eaf0;padding:13px 3px}.list{width:100%;border:0;border-bottom:1px solid #e5eaf0;background:none;padding:14px;text-align:left}.list.selected{color:#1769ed}.form,.note{display:grid;gap:12px;max-width:760px}.form textarea,.note textarea{min-height:120px}.note{max-width:none;grid-template-columns:2fr 90px 3fr auto;margin-top:16px;align-items:end}.compare{display:grid;grid-template-columns:120px repeat(4,minmax(130px,1fr));padding:12px;border-bottom:1px solid #ddd;text-transform:capitalize;overflow:auto}.alert{padding:12px;border-radius:10px}.err{background:#fee2e2;color:#991b1b}.ok{background:#dcfce7;color:#166534}@media(max-width:760px){.club{padding:14px}.metrics,.grid{grid-template-columns:1fr}.hero svg{display:none}.inline,.note{display:grid;grid-template-columns:1fr}.row{flex-wrap:wrap}}</style>
