<?php

namespace App\Filament\Resources\FeedSettings\Pages;

use App\Filament\Resources\FeedSettings\FeedSettingResource;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\EditRecord;

class EditFeedSetting extends EditRecord
{
    protected static string $resource = FeedSettingResource::class;

    protected function mutateFormDataBeforeSave(array $data): array
    {
        $data['updated_by'] = auth()->id();
        return $data;
    }

    protected function afterSave(): void
    {
        Notification::make()
            ->success()
            ->title('Feed algorithm updated')
            ->body('Web and mobile now use these settings. Precomputed feeds will be regenerated by the scheduled feed worker.')
            ->send();
    }
}
