<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { MapPin } from '@lucide/vue';

const props=withDefaults(defineProps<{modelValue?:string;placeholder?:string;country?:string}>(),{modelValue:'',placeholder:'Search for a city, venue, suburb or address',country:'za'});
const emit=defineEmits<{(event:'update:modelValue',value:string):void;(event:'place',value:any):void}>();
const host=ref<HTMLElement|null>(null),manual=ref(props.modelValue),unavailable=ref(false),loading=ref(true);let element:any;
const key=import.meta.env.VITE_GOOGLE_MAPS_API_KEY as string|undefined;
let googleLoader:Promise<any>|undefined;
const loadGoogle=()=>{if((window as any).google?.maps)return Promise.resolve((window as any).google);if(googleLoader)return googleLoader;if(!key)return Promise.reject(new Error('Google Maps key is not configured.'));googleLoader=new Promise((resolve,reject)=>{const callback=`suGoogleMaps${Date.now()}`;(window as any)[callback]=()=>{delete (window as any)[callback];resolve((window as any).google)};const script=document.createElement('script');script.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(key)}&loading=async&libraries=places&callback=${callback}`;script.async=true;script.onerror=()=>reject(new Error('Google Maps could not load.'));document.head.appendChild(script)});return googleLoader};
const component=(components:any[],type:string)=>components?.find(item=>item.types?.includes(type));
const selected=async(event:any)=>{const place=event.placePrediction?.toPlace?.();if(!place)return;await place.fetchFields({fields:['displayName','formattedAddress','location','addressComponents']});const parts=place.addressComponents??[],country=component(parts,'country'),province=component(parts,'administrative_area_level_1'),city=component(parts,'locality')??component(parts,'postal_town')??component(parts,'administrative_area_level_2'),locality=component(parts,'sublocality_level_1')??component(parts,'sublocality')??component(parts,'neighborhood');const value=place.formattedAddress||place.displayName||'';emit('update:modelValue',value);emit('place',{name:value,country:country?.shortText??'',province:province?.longText??'',city:city?.longText??'',locality:locality?.longText??'',latitude:place.location?.lat?.()??null,longitude:place.location?.lng?.()??null,place_id:place.id??null})};
onMounted(async()=>{if(!key){unavailable.value=true;loading.value=false;return}try{const google=await loadGoogle();const {PlaceAutocompleteElement}=await google.maps.importLibrary('places');element=new PlaceAutocompleteElement({includedRegionCodes:props.country?[props.country.toLowerCase()]:undefined,placeholder:props.placeholder,requestedRegion:props.country?.toLowerCase()});element.value=props.modelValue;element.className='google-place-element';element.addEventListener('gmp-select',selected);host.value?.appendChild(element)}catch{unavailable.value=true}finally{loading.value=false}});
watch(()=>props.modelValue,value=>{manual.value=value;if(element&&element.value!==value)element.value=value??''});
onBeforeUnmount(()=>element?.removeEventListener('gmp-select',selected));
</script>
<template><div class="place-wrap"><MapPin/><div v-if="!unavailable" ref="host" class="place-host"><span v-if="loading">Loading Google locations…</span></div><input v-else v-model="manual" :placeholder="placeholder" @input="emit('update:modelValue',manual)"/><small v-if="unavailable">Manual entry · add VITE_GOOGLE_MAPS_API_KEY to enable Google suggestions</small></div></template>
<style scoped>.place-wrap{position:relative}.place-wrap>svg{position:absolute;z-index:2;left:12px;top:13px;width:17px;color:#69768b}.place-host,.place-wrap>input{width:100%;min-height:44px;box-sizing:border-box;border:1px solid #d9e0ea;border-radius:10px;background:#fff}.place-host{display:flex;align-items:center;color:#8a95a6;font-size:13px}.place-host>span{padding-left:40px}.place-wrap>input{padding:11px 12px 11px 39px;font:inherit}.place-wrap small{display:block;margin-top:5px;color:#8a95a6;font-size:10px}:deep(.google-place-element){width:100%;border:0;background:transparent;color:inherit}</style>
