<script setup lang="ts">
import { MapPin } from '@lucide/vue';
import { onBeforeUnmount, onMounted, ref, watch } from 'vue';
const props=withDefaults(defineProps<{modelValue?:string;placeholder?:string;country?:string}>(),{modelValue:'',placeholder:'Search for a city, venue, suburb or address',country:'za'});
const emit=defineEmits<{(event:'update:modelValue',value:string):void;(event:'place',value:any):void}>();
const root=ref<HTMLElement|null>(null),query=ref(props.modelValue),results=ref<any[]>([]),loading=ref(false),error=ref(''),open=ref(false);
let timer:ReturnType<typeof setTimeout>|null=null,controller:AbortController|null=null;
const search=()=>{emit('update:modelValue',query.value);if(timer)clearTimeout(timer);controller?.abort();error.value='';if(query.value.trim().length<3){results.value=[];open.value=false;return}timer=setTimeout(async()=>{controller=new AbortController();loading.value=true;try{const params=new URLSearchParams({q:query.value.trim(),format:'jsonv2',addressdetails:'1',limit:'6','accept-language':navigator.language||'en'});if(props.country)params.set('countrycodes',props.country.toLowerCase());const response=await fetch(`https://nominatim.openstreetmap.org/search?${params}`,{signal:controller.signal,headers:{Accept:'application/json'}});if(!response.ok)throw new Error('Location search is temporarily unavailable.');results.value=await response.json();open.value=true}catch(exception:any){if(exception.name!=='AbortError')error.value=exception.message}finally{loading.value=false}},1000)};
const select=(result:any)=>{const address=result.address??{},value=result.display_name??'';query.value=value;results.value=[];open.value=false;emit('update:modelValue',value);emit('place',{name:value,country:String(address.country_code??'').toUpperCase(),province:address.state??address.province??address.region??'',city:address.city??address.town??address.village??address.municipality??address.county??'',locality:address.suburb??address.neighbourhood??address.quarter??address.city_district??'',latitude:Number(result.lat)||null,longitude:Number(result.lon)||null,place_id:result.place_id?String(result.place_id):null,osm_type:result.osm_type??null,osm_id:result.osm_id?String(result.osm_id):null})};
const closeAway=(event:PointerEvent)=>{if(!root.value?.contains(event.target as Node))open.value=false};
watch(()=>props.modelValue,value=>{if(value!==query.value)query.value=value??''});
onMounted(()=>document.addEventListener('pointerdown',closeAway));
onBeforeUnmount(()=>{if(timer)clearTimeout(timer);controller?.abort();document.removeEventListener('pointerdown',closeAway)});
</script>
<template><div ref="root" class="place-wrap"><MapPin/><input v-model="query" role="combobox" :aria-expanded="open" aria-autocomplete="list" :placeholder="placeholder" @input="search" @focus="open=results.length>0" @keydown.escape="open=false"/><span v-if="loading" class="place-loading">Searching…</span><ul v-if="open" class="place-results" role="listbox"><li v-for="result in results" :key="result.place_id"><button type="button" role="option" @click="select(result)"><strong>{{result.name||result.display_name.split(',')[0]}}</strong><small>{{result.display_name}}</small></button></li><li v-if="!results.length&&!loading" class="place-empty">No matching locations found.</li></ul><small v-if="error" class="place-error">{{error}} You can still enter the location manually.</small><small class="place-credit">Search © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">OpenStreetMap contributors</a></small></div></template>
<style scoped>.place-wrap{position:relative}.place-wrap>svg{position:absolute;z-index:2;top:13px;left:12px;width:17px;color:#69768b}.place-wrap>input{box-sizing:border-box;width:100%;min-height:44px;padding:11px 76px 11px 39px;border:1px solid #d9e0ea;border-radius:10px;background:#fff;font:inherit}.place-loading{position:absolute;top:15px;right:12px;color:#7c8797;font-size:11px}.place-results{position:absolute;z-index:30;top:47px;right:0;left:0;max-height:280px;overflow:auto;margin:0;padding:5px;list-style:none;border:1px solid #d9e0ea;border-radius:12px;background:#fff;box-shadow:0 15px 35px rgba(20,35,55,.16)}.place-results button{display:grid;width:100%;gap:3px;padding:9px;text-align:left;border:0;border-radius:8px;background:transparent;cursor:pointer}.place-results button:hover,.place-results button:focus{background:#eef4ff}.place-results strong{color:#243148;font-size:12px}.place-results small{overflow:hidden;color:#748196;font-size:10px;text-overflow:ellipsis;white-space:nowrap}.place-empty{padding:12px;color:#7c8797;font-size:11px}.place-credit,.place-error{display:block;margin-top:5px;color:#8a95a6;font-size:10px}.place-credit a{color:#526b9e;text-decoration:underline}.place-error{color:#b54762}</style>
