import { useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useMutation } from '@tanstack/react-query';
import { api } from '../../src/api/client';
import { PrimaryButton } from '../../src/components/PrimaryButton';
import { colors, radius, spacing } from '../../src/theme';

const reasons = ['spam', 'harassment', 'hate', 'nudity', 'violence', 'fraud', 'impersonation', 'copyright', 'other'] as const;
export default function ReportScreen() {
  const params = useLocalSearchParams<{ type: 'video' | 'comment' | 'media' | 'message' | 'user' | 'conversation'; id: string; label?: string }>();
  const [reason, setReason] = useState<typeof reasons[number]>();
  const [details, setDetails] = useState('');
  const report = useMutation({ mutationFn: () => params.type === 'conversation' ? api.post(`/conversations/${params.id}/report`, { reason, details: details.trim() || undefined }) : api.post('/reports', { type: params.type, id: params.id, reason, details: details.trim() || undefined }), onSuccess: () => Alert.alert('Report submitted', 'Our safety team will review it. We will not tell the reported member who submitted the report.', [{ text: 'Done', onPress: () => router.back() }]), onError: (error: any) => Alert.alert('Report not submitted', error?.response?.data?.message || 'Please try again.') });
  return <SafeAreaView edges={['top']} style={styles.safe}><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={styles.header}><Pressable accessibilityLabel="Go back" onPress={() => router.back()}><Ionicons name="chevron-back" size={26} color="#fff" /></Pressable><Text style={styles.headerTitle}>Report</Text><View style={{ width: 26 }} /></View><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.safetyIcon}><Ionicons name="shield-outline" size={31} color="#79A3FF" /></View><Text style={styles.title}>Help keep SportsUniverse safe.</Text><Text style={styles.copy}>Why are you reporting {params.label || 'this content'}?</Text><View style={styles.reasons}>{reasons.map(value => <Pressable key={value} onPress={() => setReason(value)} style={[styles.reason, reason === value && styles.reasonActive]}><Text style={[styles.reasonText, reason === value && styles.reasonTextActive]}>{value}</Text><Ionicons name={reason === value ? 'radio-button-on' : 'radio-button-off'} size={19} color={reason === value ? colors.blue : colors.muted} /></Pressable>)}</View><Text style={styles.label}>Additional details (optional)</Text><TextInput value={details} onChangeText={setDetails} multiline maxLength={5000} placeholder="Provide context that will help our review…" placeholderTextColor="#71849B" style={styles.details} textAlignVertical="top" /><Text style={styles.counter}>{details.length}/5000</Text><PrimaryButton label="Submit report" loading={report.isPending} disabled={!reason} onPress={() => report.mutate()} style={{ marginTop: 18 }} /></ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.navy }, flex: { flex: 1 }, header: { height: 56, paddingHorizontal: spacing.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.line }, headerTitle: { color: '#fff', fontSize: 17, fontWeight: '900' }, content: { padding: spacing.lg, paddingBottom: 45 }, safetyIcon: { width: 58, height: 58, borderRadius: 29, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(71,111,234,.14)' }, title: { color: '#fff', fontSize: 28, lineHeight: 32, fontWeight: '900', marginTop: 16 }, copy: { color: colors.muted, fontSize: 14, lineHeight: 20, marginTop: 7, marginBottom: 19 }, reasons: { overflow: 'hidden', borderRadius: radius.lg, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface }, reason: { minHeight: 51, paddingHorizontal: 15, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.line }, reasonActive: { backgroundColor: 'rgba(71,111,234,.1)' }, reasonText: { color: '#D9E4F1', fontSize: 13, fontWeight: '700', textTransform: 'capitalize' }, reasonTextActive: { color: '#fff' }, label: { color: '#DCE7F5', fontSize: 12, fontWeight: '800', marginTop: 22, marginBottom: 7 }, details: { height: 130, padding: 14, borderRadius: radius.md, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface, color: '#fff' }, counter: { color: colors.muted, fontSize: 10, textAlign: 'right', marginTop: 5 } });
