import { Alert, FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '../../../src/api/client';
import { ScreenMessage } from '../../../src/components/ScreenMessage';
import { colors, radius, spacing } from '../../../src/theme';
import type { Opportunity, PaginatedResponse } from '../../../src/types/api';

export default function ManageOpportunitiesScreen() {
  const client = useQueryClient();
  const opportunities = useQuery({ queryKey: ['opportunities', 'mine'], queryFn: async () => (await api.get<PaginatedResponse<Opportunity>>('/opportunities/mine')).data.data });
  const action = useMutation({ mutationFn: ({ id, kind }: { id: string; kind: 'cancel' | 'delete' }) => kind === 'cancel' ? api.post('/opportunities/' + id + '/cancel') : api.delete('/opportunities/' + id), onSuccess: () => { client.invalidateQueries({ queryKey: ['opportunities'] }); }, onError: (error: any) => Alert.alert('Action failed', error?.response?.data?.message || 'Please try again.') });
  const confirm = (item: Opportunity) => { const kind = item.applications_count ? 'cancel' : 'delete'; Alert.alert(kind === 'cancel' ? 'Cancel opportunity?' : 'Delete opportunity?', kind === 'cancel' ? 'Applications will remain available for your records, but no new applications will be accepted.' : 'This draft or opportunity will be permanently removed.', [{ text: 'Keep it', style: 'cancel' }, { text: kind === 'cancel' ? 'Cancel opportunity' : 'Delete', style: 'destructive', onPress: () => action.mutate({ id: item.id, kind }) }]); };
  const items = opportunities.data ?? [];
  return <SafeAreaView edges={['top']} style={styles.safe}><View style={styles.header}><Pressable accessibilityLabel="Go back" onPress={() => router.back()}><Ionicons name="chevron-back" size={26} color="#fff" /></Pressable><Text style={styles.headerTitle}>Manage opportunities</Text><Pressable accessibilityLabel="Create opportunity" onPress={() => router.push('/opportunity/editor')}><Ionicons name="add-circle-outline" size={25} color="#fff" /></Pressable></View><FlatList data={items} keyExtractor={item => item.id} contentContainerStyle={items.length ? styles.list : styles.empty} refreshing={opportunities.isRefetching} onRefresh={() => opportunities.refetch()} ItemSeparatorComponent={() => <View style={{ height: 10 }} />} ListEmptyComponent={<ScreenMessage icon="briefcase-outline" title="No opportunities yet" message="Create a trial, job, camp, sponsorship, scout day or academy application." />} renderItem={({ item }) => <View style={styles.card}><View style={styles.cardTop}><View style={[styles.status, item.status === 'draft' && styles.draft, item.status === 'cancelled' && styles.cancelled]}><Text style={styles.statusText}>{item.status}</Text></View><Text style={styles.type}>{item.type.replaceAll('_', ' ')}</Text></View><Text style={styles.title}>{item.title}</Text><Text style={styles.meta}>{item.applications_count} applications · {item.deadline ? `Closes ${new Date(item.deadline).toLocaleDateString()}` : 'Open until filled'}</Text><View style={styles.actions}><Pressable onPress={() => router.push({ pathname: '/opportunity/editor', params: { id: item.id } })} style={styles.button}><Ionicons name="create-outline" size={17} color="#fff" /><Text style={styles.buttonText}>Edit</Text></Pressable><Pressable onPress={() => router.push(`/opportunity/${item.id}/applicants` as never)} style={[styles.button, styles.primary]}><Ionicons name="people-outline" size={17} color="#fff" /><Text style={styles.buttonText}>Applicants</Text></Pressable>{item.status !== 'cancelled' ? <Pressable onPress={() => confirm(item)} style={styles.iconButton}><Ionicons name={item.applications_count ? 'close-circle-outline' : 'trash-outline'} size={19} color={colors.danger} /></Pressable> : null}</View></View>} /></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.navy }, header: { height: 56, paddingHorizontal: spacing.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.line }, headerTitle: { color: '#fff', fontSize: 17, fontWeight: '900' }, list: { padding: spacing.md, paddingBottom: 40 }, empty: { flexGrow: 1 }, card: { padding: spacing.md, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface }, cardTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, status: { paddingHorizontal: 8, paddingVertical: 5, borderRadius: 7, backgroundColor: colors.green }, draft: { backgroundColor: colors.orange }, cancelled: { backgroundColor: colors.danger }, statusText: { color: '#fff', fontSize: 9, fontWeight: '900', textTransform: 'uppercase' }, type: { color: colors.muted, fontSize: 10, fontWeight: '800', textTransform: 'capitalize' }, title: { color: '#fff', fontSize: 18, fontWeight: '900', marginTop: 12 }, meta: { color: colors.muted, fontSize: 11, marginTop: 7 }, actions: { flexDirection: 'row', gap: 7, marginTop: 15 }, button: { minHeight: 37, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 6, borderRadius: 9, backgroundColor: colors.surfaceRaised }, primary: { backgroundColor: colors.blue }, buttonText: { color: '#fff', fontSize: 11, fontWeight: '800' }, iconButton: { width: 37, height: 37, marginLeft: 'auto', alignItems: 'center', justifyContent: 'center', borderRadius: 9, backgroundColor: 'rgba(255,107,129,.08)' } });
