import { ActivityIndicator, FlatList, Image, Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useQuery } from '@tanstack/react-query';
import { BrandMark } from '../../src/components/BrandMark';
import { PrimaryButton } from '../../src/components/PrimaryButton';
import { ScreenMessage } from '../../src/components/ScreenMessage';
import { api } from '../../src/api/client';
import { useAuthStore } from '../../src/stores/auth';
import { colors, radius, spacing } from '../../src/theme';
import type { ApiResponse, LiveStream } from '../../src/types/api';
import { absoluteMediaUrl } from '../../src/utils/url';

export default function LiveScreen() {
  const user = useAuthStore(state => state.user);
  const streams = useQuery({ queryKey: ['live'], queryFn: async () => (await api.get<ApiResponse<LiveStream[]>>('/live')).data.data, refetchInterval: 10000 });
  return <SafeAreaView edges={['top']} style={styles.safe}><View style={styles.header}><BrandMark /><View style={styles.liveHeading}><View style={styles.liveDot} /><Text style={styles.headerTitle}>Live now</Text></View></View>
    <FlatList data={streams.data ?? []} keyExtractor={item => item.id} contentContainerStyle={styles.list} refreshControl={<RefreshControl refreshing={streams.isRefetching} onRefresh={() => streams.refetch()} tintColor={colors.blue} />} ListHeaderComponent={<View style={styles.intro}><Text style={styles.title}>Watch sport happen live.</Text><Text style={styles.copy}>Training sessions, trials, matches and athlete conversations—happening now.</Text>{user ? <PrimaryButton label="Go live" onPress={() => router.push('/live/create')} style={{ marginTop: 17 }} /> : null}</View>} ItemSeparatorComponent={() => <View style={{ height: 14 }} />} renderItem={({ item }) => <LiveCard stream={item} signedIn={Boolean(user)} />} ListEmptyComponent={streams.isLoading ? <ActivityIndicator style={styles.loader} color={colors.blue} /> : streams.isError ? <ScreenMessage icon="cloud-offline-outline" title="Live streams unavailable" message="Check your connection and try again." action={<PrimaryButton label="Try again" secondary onPress={() => streams.refetch()} />} /> : <ScreenMessage icon="radio-outline" title="Nobody is live right now" message="Active broadcasts will appear here automatically." />} />
  </SafeAreaView>;
}

function LiveCard({ stream, signedIn }: { stream: LiveStream; signedIn: boolean }) {
  const image = absoluteMediaUrl(stream.image);
  return <Pressable accessibilityRole="button" onPress={() => signedIn ? router.push(`/live/${stream.id}` as never) : router.push('/(auth)/login')} style={({ pressed }) => [styles.card, pressed && { opacity: .78 }]}><View style={styles.preview}>{image ? <Image source={{ uri: image }} style={styles.image} /> : <View style={styles.placeholder}><Ionicons name="videocam" size={38} color="#79A3FF" /></View>}<View style={styles.badge}><View style={styles.badgeDot} /><Text style={styles.badgeText}>LIVE</Text></View><View style={styles.viewers}><Ionicons name="eye" size={14} color="#fff" /><Text style={styles.viewerText}>{stream.viewer_count}</Text></View></View><View style={styles.cardBody}><View style={styles.avatar}><Text style={styles.initials}>{stream.host_name.split(/\s+/).slice(0, 2).map(part => part[0]).join('').toUpperCase()}</Text></View><View style={{ flex: 1 }}><Text numberOfLines={2} style={styles.streamTitle}>{stream.title}</Text><Text style={styles.host}>{stream.host_name}</Text>{stream.description ? <Text numberOfLines={2} style={styles.description}>{stream.description}</Text> : null}</View><Ionicons name="chevron-forward" size={20} color={colors.muted} /></View></Pressable>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.navy }, header: { height: 58, paddingHorizontal: spacing.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.line }, liveHeading: { flexDirection: 'row', alignItems: 'center', gap: 7 }, liveDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.pink }, headerTitle: { color: colors.white, fontSize: 15, fontWeight: '900' }, list: { flexGrow: 1, padding: spacing.md }, intro: { paddingVertical: 12, paddingBottom: 22 }, title: { color: colors.white, fontSize: 27, fontWeight: '900', letterSpacing: -.8 }, copy: { color: colors.muted, fontSize: 13, lineHeight: 20, marginTop: 6 }, loader: { marginTop: 100 }, card: { overflow: 'hidden', borderRadius: radius.lg, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface }, preview: { height: 180, backgroundColor: colors.navyLight }, image: { width: '100%', height: '100%', resizeMode: 'cover' }, placeholder: { flex: 1, alignItems: 'center', justifyContent: 'center' }, badge: { position: 'absolute', left: 12, top: 12, flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 9, paddingVertical: 6, borderRadius: radius.sm, backgroundColor: colors.pink }, badgeDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#fff' }, badgeText: { color: '#fff', fontSize: 10, fontWeight: '900' }, viewers: { position: 'absolute', right: 12, top: 12, flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 9, paddingVertical: 6, borderRadius: radius.sm, backgroundColor: 'rgba(0,0,0,.65)' }, viewerText: { color: '#fff', fontSize: 10, fontWeight: '900' }, cardBody: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 14 }, avatar: { width: 43, height: 43, borderRadius: 22, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.blue }, initials: { color: '#fff', fontSize: 12, fontWeight: '900' }, streamTitle: { color: colors.white, fontSize: 16, fontWeight: '900' }, host: { color: '#79A3FF', fontSize: 11, fontWeight: '800', marginTop: 3 }, description: { color: colors.muted, fontSize: 11, lineHeight: 16, marginTop: 5 } });
