import { Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { BrandMark } from '../../src/components/BrandMark';
import { PrimaryButton } from '../../src/components/PrimaryButton';
import { useAuthStore } from '../../src/stores/auth';
import { colors, radius, spacing } from '../../src/theme';

export default function ProfileScreen(){const {user,logout}=useAuthStore();if(!user)return <SafeAreaView style={styles.safe}><BrandMark/><View style={styles.center}><Ionicons name="person-circle" size={76} color={colors.blue}/><Text style={styles.title}>Build your sports identity.</Text><Text style={styles.copy}>Create a profile to follow talent, save highlights and discover opportunities.</Text><PrimaryButton label="Create free account" onPress={()=>router.push('/(auth)/register')} style={{width:'100%',marginTop:22}}/><PrimaryButton label="Sign in" secondary onPress={()=>router.push('/(auth)/login')} style={{width:'100%',marginTop:10}}/></View></SafeAreaView>;const signOut=async()=>{await logout();router.replace('/(tabs)/feed');};return <SafeAreaView style={styles.safe}><BrandMark/><View style={styles.card}><View style={styles.avatar}><Text style={styles.avatarText}>{user.name[0]}</Text></View><Text style={styles.name}>{user.name}</Text><Text style={styles.role}>{user.roles?.[0]||'SportUniverse member'}</Text><View style={styles.progressRow}><Text style={styles.muted}>Profile completeness</Text><Text style={styles.percent}>{user.profile?.completeness??35}%</Text></View><View style={styles.progress}><View style={[styles.progressFill,{width:`${user.profile?.completeness??35}%`} as any]}/></View></View><Pressable style={styles.logout} onPress={signOut}><Ionicons name="log-out-outline" size={20} color={colors.danger}/><Text style={styles.logoutText}>Sign out</Text></Pressable></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.navy,padding:spacing.lg},center:{flex:1,alignItems:'center',justifyContent:'center'},title:{color:colors.white,fontSize:28,fontWeight:'900',textAlign:'center',letterSpacing:-1,marginTop:14},copy:{color:colors.muted,textAlign:'center',lineHeight:21,maxWidth:320,marginTop:8},card:{marginTop:40,padding:spacing.lg,borderWidth:1,borderColor:colors.line,borderRadius:radius.lg,backgroundColor:colors.surface,alignItems:'center'},avatar:{width:82,height:82,borderRadius:41,backgroundColor:colors.blue,alignItems:'center',justifyContent:'center'},avatarText:{color:'#fff',fontSize:32,fontWeight:'900'},name:{color:'#fff',fontSize:24,fontWeight:'900',marginTop:14},role:{color:'#79A3FF',fontWeight:'700',textTransform:'capitalize',marginTop:3},progressRow:{width:'100%',flexDirection:'row',justifyContent:'space-between',marginTop:26},muted:{color:colors.muted},percent:{color:'#fff',fontWeight:'900'},progress:{width:'100%',height:8,borderRadius:8,backgroundColor:'rgba(255,255,255,.09)',marginTop:8,overflow:'hidden'},progressFill:{height:'100%',backgroundColor:colors.green},logout:{marginTop:20,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8,padding:14},logoutText:{color:colors.danger,fontWeight:'800'}});
