import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useQuery } from '@tanstack/react-query';
import { BrandMark } from '../../src/components/BrandMark';
import { PrimaryButton } from '../../src/components/PrimaryButton';
import { api } from '../../src/api/client';
import { useAuthStore } from '../../src/stores/auth';
import { colors, radius, spacing } from '../../src/theme';
import type { ApiResponse, Profile } from '../../src/types/api';
import { absoluteMediaUrl } from '../../src/utils/url';

export default function ProfileScreen() {
  const { user, logout } = useAuthStore();
  const profile = useQuery({ queryKey: ['profile', 'mine'], enabled: Boolean(user), queryFn: async () => (await api.get<ApiResponse<Profile>>('/profile')).data.data });
  if (!user) return <GuestProfile />;
  if (profile.isLoading) return <SafeAreaView style={styles.safe}><BrandMark /><ActivityIndicator style={{ flex: 1 }} color={colors.blue} /></SafeAreaView>;
  const item = profile.data;
  const image = absoluteMediaUrl(item?.images.profile);
  const completeness = Number(item?.completeness ?? user.profile?.completeness ?? 35);
  const signOut = async () => { await logout(); router.replace('/(tabs)/feed'); };

  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}>
    <View style={styles.header}><BrandMark /><View style={styles.headerActions}><HeaderButton label="Creator analytics" icon="stats-chart-outline" onPress={() => router.push('/analytics')} />{user.roles.includes('athlete') ? <HeaderButton label="Career portfolio" icon="trophy-outline" onPress={() => router.push('/profile/career')} /> : null}<HeaderButton label="My posts" icon="albums-outline" onPress={() => router.push('/profile/my-posts')} /><HeaderButton label="Edit profile" icon="create-outline" onPress={() => router.push('/profile/edit')} /><HeaderButton label="Settings" icon="settings-outline" onPress={() => router.push('/settings')} /></View></View>
    <View style={styles.card}>{image ? <Image source={{ uri: image }} style={styles.avatarImage} /> : <View style={styles.avatar}><Text style={styles.avatarText}>{user.name[0]}</Text></View>}<Text style={styles.name}>{item?.name ?? user.name}</Text><Text style={styles.role}>{item?.athlete?.sport?.name ?? user.roles?.[0] ?? 'SportsUniverse member'}</Text>{item?.location.city ? <Text style={styles.location}><Ionicons name="location-outline" size={13} /> {item.location.city}</Text> : null}<View style={styles.connectionStats}><ConnectionStat value={item?.connections?.following ?? 0} label="Following" onPress={() => router.push({ pathname: '/profile/connections', params: { userId: String(user.id), tab: 'following', name: item?.name ?? user.name } })} /><ConnectionStat value={item?.connections?.followers ?? 0} label="Followers" onPress={() => router.push({ pathname: '/profile/connections', params: { userId: String(user.id), tab: 'followers', name: item?.name ?? user.name } })} /></View><View style={styles.progressRow}><Text style={styles.muted}>Profile completeness</Text><Text style={styles.percent}>{completeness}%</Text></View><View style={styles.progress}><View style={[styles.progressFill, { width: `${completeness}%` } as any]} /></View><PrimaryButton label="Open my dashboard" onPress={() => router.push('/dashboard')} style={{ width: '100%', marginTop: 22 }} /><PrimaryButton label="Edit profile" secondary onPress={() => router.push('/profile/edit')} style={{ width: '100%', marginTop: 10 }} />{user.roles.includes('fan') ? <PrimaryButton label="Sports & favourites" secondary onPress={() => router.push('/profile/fan-preferences')} style={{ width: '100%', marginTop: 10 }} /> : null}{user.roles.includes('athlete') ? <PrimaryButton label="Manage career portfolio" secondary onPress={() => router.push('/profile/career')} style={{ width: '100%', marginTop: 10 }} /> : null}{user.roles.some(role => ['club', 'academy', 'scout', 'agent', 'admin'].includes(role)) ? <PrimaryButton label="Club & scout workspace" secondary onPress={() => router.push('/club')} style={{ width: '100%', marginTop: 10 }} /> : null}<PrimaryButton label="Manage my posts" secondary onPress={() => router.push('/profile/my-posts')} style={{ width: '100%', marginTop: 10 }} /><PrimaryButton label="Saved talent" secondary onPress={() => router.push('/profile/saved')} style={{ width: '100%', marginTop: 10 }} /><PrimaryButton label="Documents & media library" secondary onPress={() => router.push('/profile/library')} style={{ width: '100%', marginTop: 10 }} /><PrimaryButton label="Advertising & sponsorship" secondary onPress={() => router.push('/promote')} style={{ width: '100%', marginTop: 10 }} /></View>
    <Pressable style={styles.logout} onPress={signOut}><Ionicons name="log-out-outline" size={20} color={colors.danger} /><Text style={styles.logoutText}>Sign out</Text></Pressable>
  </ScrollView></SafeAreaView>;
}

function GuestProfile() { return <SafeAreaView style={styles.safe}><BrandMark /><View style={styles.center}><Ionicons name="person-circle" size={76} color={colors.blue} /><Text style={styles.guestTitle}>Build your sports identity.</Text><Text style={styles.copy}>Create a profile to follow talent, save highlights and discover opportunities.</Text><PrimaryButton label="Create free account" onPress={() => router.push('/(auth)/register')} style={{ width: '100%', marginTop: 22 }} /><PrimaryButton label="Sign in" secondary onPress={() => router.push('/(auth)/login')} style={{ width: '100%', marginTop: 10 }} /></View></SafeAreaView>; }
function HeaderButton({ label, icon, onPress }: { label: string; icon: keyof typeof Ionicons.glyphMap; onPress: () => void }) { return <Pressable accessibilityLabel={label} onPress={onPress} style={styles.editIcon}><Ionicons name={icon} size={20} color="#fff" /></Pressable>; }
function ConnectionStat({ value, label, onPress }: { value: number; label: string; onPress: () => void }) { return <Pressable onPress={onPress} style={styles.connectionStat}><Text style={styles.connectionValue}>{value}</Text><Text style={styles.muted}>{label}</Text></Pressable>; }

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.navy }, content: { flexGrow: 1, padding: spacing.lg }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, headerActions: { flexDirection: 'row', gap: 7 }, editIcon: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surface }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, guestTitle: { color: colors.white, fontSize: 28, fontWeight: '900', textAlign: 'center', letterSpacing: -1, marginTop: 14 }, copy: { color: colors.muted, textAlign: 'center', lineHeight: 21, maxWidth: 320, marginTop: 8 }, card: { marginTop: 38, padding: spacing.lg, borderWidth: 1, borderColor: colors.line, borderRadius: radius.lg, backgroundColor: colors.surface, alignItems: 'center' }, avatar: { width: 92, height: 92, borderRadius: 46, backgroundColor: colors.blue, alignItems: 'center', justifyContent: 'center' }, avatarImage: { width: 92, height: 92, borderRadius: 46, backgroundColor: colors.surfaceRaised }, avatarText: { color: '#fff', fontSize: 34, fontWeight: '900' }, name: { color: '#fff', fontSize: 24, fontWeight: '900', marginTop: 14 }, role: { color: '#79A3FF', fontWeight: '700', textTransform: 'capitalize', marginTop: 3 }, location: { color: colors.muted, fontSize: 12, marginTop: 8 }, connectionStats: { flexDirection: 'row', gap: 28, marginTop: 18 }, connectionStat: { alignItems: 'center', minWidth: 68 }, connectionValue: { color: '#fff', fontSize: 17, fontWeight: '900' }, progressRow: { width: '100%', flexDirection: 'row', justifyContent: 'space-between', marginTop: 26 }, muted: { color: colors.muted }, percent: { color: '#fff', fontWeight: '900' }, progress: { width: '100%', height: 8, borderRadius: 8, backgroundColor: 'rgba(255,255,255,.09)', marginTop: 8, overflow: 'hidden' }, progressFill: { height: '100%', backgroundColor: colors.green }, logout: { marginTop: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, padding: 14 }, logoutText: { color: colors.danger, fontWeight: '800' } });
