<script setup lang="ts">
import { Head, Link } from '@inertiajs/vue3';
import { ArrowRight, BriefcaseBusiness, CircleEllipsis, CirclePlay, Eye, Flame, Heart, Trophy, Upload, UserRound, UsersRound } from '@lucide/vue';
import { computed, ref } from 'vue';
import PublicNavbar from '../../Components/Public/PublicNavbar.vue';
import PublicFooter from '../../Components/Public/PublicFooter.vue';
const props=defineProps<{highlights:any[];athletes:any[];sports:any[];opportunities:any[];stats:Record<string,number>}>();
const slide=ref(0);const visibleHighlights=computed(()=>props.highlights.slice(slide.value,slide.value+4));
const move=(direction:number)=>{const maximum=Math.max(0,props.highlights.length-4);slide.value=Math.min(maximum,Math.max(0,slide.value+direction))};
const compact=(value:number)=>new Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(value||0);
const sportIcons=['⚽','🏉','🏃','🏀','🏏','◉','🎾','•••'];
const statItems=computed(()=>[{value:props.stats.athletes,label:'Athletes',icon:'♙'},{value:props.stats.sports,label:'Sports',icon:'♕'},{value:props.stats.opportunities,label:'Opportunities',icon:'♜'},{value:props.stats.highlights,label:'Videos Uploaded',icon:'▣'}].filter(item=>item.value));
</script>
<template>
<Head title="Where Sports Talent Meets Opportunity"><meta name="description" content="Discover athletes, watch sports highlights and connect talent with scouts, clubs, coaches and sporting opportunities on SportsUniverse."/></Head>
<div class="public-home portal-home"><PublicNavbar/><main id="main-content" class="portal-main">
<section class="portal-hero public-container"><img class="portal-hero-art" :src="'/images/homepage-hero.png'" alt="Football, rugby, athletics, basketball and cricket athletes"/><div class="portal-hero-shade"/><div class="portal-hero-copy"><h1>Where sports<br/>talent meets<br/><span>opportunity</span></h1><p>Showcase your talent. Share your highlights. Get discovered by scouts, coaches, clubs, and academies around the world.</p><div class="portal-actions"><Link href="/register" class="portal-primary">Join SportsUniverse <ArrowRight/></Link><a href="#athletes" class="portal-secondary">Explore Athletes</a><a href="#highlights" class="portal-watch"><CirclePlay/> Watch Highlights</a></div></div></section>
<section id="highlights" class="portal-discovery public-container"><div class="portal-highlights"><header class="portal-title"><h2><Flame/> Top athlete highlights</h2><Link href="/feed">View all <ArrowRight/></Link></header><div class="portal-highlight-grid"><a v-for="item in visibleHighlights" :key="item.id" :href="`/feed#${item.id}`" class="portal-video-card"><div class="portal-video"><img v-if="item.cover" :src="item.cover" :alt="`${item.athlete.name} highlight`" loading="lazy"/><video v-else-if="item.video" :src="item.video" muted preload="metadata" playsinline/><div v-else class="portal-video-empty">{{ item.sport?.slice(0,1) }}</div><CirclePlay/></div><div class="portal-video-copy"><span class="public-avatar"><img v-if="item.athlete.image" :src="item.athlete.image" alt=""/><b v-else>{{ item.athlete.name.slice(0,2) }}</b></span><div><strong>{{ item.athlete.name }} <i>●</i></strong><small>{{ [item.sport,item.athlete.position].filter(Boolean).join(' · ') }}</small><small>{{ item.location }}</small></div></div><div class="portal-video-stats"><span><Eye/>{{ compact(item.views) }}</span><span><Heart/>{{ compact(item.likes) }}</span></div></a><div v-if="!highlights.length" class="portal-data-empty"><CirclePlay/><strong>Highlights will appear here</strong><span>Be the first athlete to share a moment.</span><Link href="/register">Join now</Link></div></div><button v-if="slide" class="portal-slider prev" aria-label="Previous highlights" @click="move(-1)">‹</button><button v-if="slide<highlights.length-4" class="portal-slider next" aria-label="Next highlights" @click="move(1)">›</button></div><aside id="sports" class="portal-sports"><header class="portal-title"><h2>Explore by sport</h2><Link href="/feed">View all <ArrowRight/></Link></header><div class="portal-sport-grid"><a v-for="(sport,index) in sports.slice(0,7)" :key="sport.slug" :href="`/feed/sport/${encodeURIComponent(sport.name)}`"><span>{{ sportIcons[index] }}</span><strong>{{ sport.name }}</strong></a><Link href="/feed"><CircleEllipsis/><strong>More Sports</strong></Link></div><Link href="/feed" class="portal-sport-total"><UsersRound/><span><strong>{{ compact(stats.athletes) }}+ Athletes</strong><small>across {{ stats.sports }} sports</small></span><b>Explore All <ArrowRight/></b></Link></aside></section>
<section class="portal-widgets public-container"><article class="portal-widget how-widget"><header class="portal-title"><h2>How it works</h2></header><div class="portal-how"><div><i><UserRound/></i><strong>Create Profile</strong><span>Build your sports profile in minutes</span></div><b>→</b><div><i><Upload/></i><strong>Upload & Share</strong><span>Add videos, stats & achievements</span></div><b>→</b><div><i><Eye/></i><strong>Get Discovered</strong><span>Scouts & coaches find your talent</span></div><b>→</b><div><i><Trophy/></i><strong>Unlock Opportunities</strong><span>Trials, scholarships & career paths</span></div></div></article><article id="athletes" class="portal-widget"><header class="portal-title"><h2>Athletes to watch</h2><Link href="/feed">View all</Link></header><div class="portal-list"><a v-for="athlete in athletes.slice(0,3)" :key="athlete.slug" :href="`/@${athlete.slug}`"><span class="public-avatar"><img v-if="athlete.image" :src="athlete.image" :alt="athlete.name"/><b v-else>{{ athlete.name.slice(0,2) }}</b></span><span><strong>{{ athlete.name }} <i>●</i></strong><small>{{ athlete.sport }} · {{ athlete.position||'Athlete' }}</small></span><b>☆</b></a><div v-if="!athletes.length" class="portal-mini-empty">Athletes will appear here.</div></div></article><article id="opportunities" class="portal-widget"><header class="portal-title"><h2>Latest opportunities</h2><Link href="/login">View all</Link></header><div class="portal-list opportunity-list"><Link v-for="opportunity in opportunities.slice(0,3)" :key="opportunity.id" href="/login"><i><BriefcaseBusiness/></i><span><strong>{{ opportunity.title }}</strong><small>{{ opportunity.host }}</small><small>{{ opportunity.location }}</small></span><b v-if="opportunity.deadline">{{ Math.max(0,Math.ceil((new Date(opportunity.deadline).getTime()-Date.now())/86400000)) }}d left</b></Link><div v-if="!opportunities.length" class="portal-mini-empty">New opportunities are coming soon.</div></div></article><article class="portal-widget stats-widget"><header class="portal-title"><h2>Platform stats</h2></header><div class="portal-stat-grid"><div v-for="item in statItems" :key="item.label"><span>{{ item.icon }}</span><p><strong>{{ compact(item.value) }}+</strong><small>{{ item.label }}</small></p></div><div v-if="!statItems.length" class="portal-mini-empty">Community numbers are growing.</div></div></article></section>
<section class="portal-scout public-container"><UsersRound/><div><strong>Are you a scout, coach or club?</strong><span>Find emerging talent. Build your team. Shape the future.</span></div><Link href="/register">Join as Scout or Club <ArrowRight/></Link><span class="portal-trust">Trusted by the sporting community</span></section><section class="portal-cta public-container"><div class="cta-athlete"><Trophy/></div><div><h2>Your talent <span>deserves to be seen.</span></h2><p>Join athletes building their legacy on SportsUniverse.</p></div><Link href="/register" class="portal-primary">Join SportsUniverse <ArrowRight/></Link><a href="#athletes" class="portal-secondary">Explore Athletes</a></section>
</main><PublicFooter/></div>
</template>
