<script setup lang="ts">
import { Head, Link } from '@inertiajs/vue3';
import { ArrowRight, Award, BriefcaseBusiness, ChevronRight, CirclePlay, Compass, MapPin, Search, ShieldCheck, Sparkles, Trophy, Upload, UserRoundPlus, UsersRound } from '@lucide/vue';
import { computed, onMounted, onUnmounted, ref } from 'vue';
import AthleteCard from '../../Components/Public/AthleteCard.vue';
import HighlightCard from '../../Components/Public/HighlightCard.vue';
import PublicFooter from '../../Components/Public/PublicFooter.vue';
import PublicNavbar from '../../Components/Public/PublicNavbar.vue';

const props = defineProps<{ highlights:any[]; athletes:any[]; sports:any[]; opportunities:any[]; stats:Record<string, number> }>();
const activeSport = ref('All');
const filteredHighlights = computed(() => activeSport.value === 'All' ? props.highlights : props.highlights.filter(item => item.sport === activeSport.value));
const filterSports = computed(() => ['All', ...new Set(props.highlights.map(item => item.sport).filter(Boolean))].slice(0, 7));
const format = (value:number) => new Intl.NumberFormat('en-ZA').format(value ?? 0);
const reveal = ref<IntersectionObserver|null>(null);
onMounted(() => { reveal.value = new IntersectionObserver(entries => entries.forEach(entry => entry.isIntersecting && entry.target.classList.add('visible')), { threshold: .12 }); document.querySelectorAll('.reveal').forEach(el => reveal.value?.observe(el)); });
onUnmounted(() => reveal.value?.disconnect());
const sportArt = ['#69a7ff','#f26ba6','#f3b94f','#6ac59a','#9b83ef','#f07d62'];
</script>

<template>
    <Head title="Where Sports Talent Meets Opportunity"><meta name="description" content="Discover athletes, watch sports highlights and connect talent with scouts, clubs, coaches and sporting opportunities on SportsUniverse." /></Head>
    <div class="public-home">
        <PublicNavbar/>
        <main id="main-content">
            <section class="public-hero">
                <div class="hero-noise"/><div class="hero-orb hero-orb-one"/><div class="hero-orb hero-orb-two"/>
                <div class="public-container hero-grid">
                    <div class="hero-copy reveal visible"><span class="public-kicker"><Sparkles/> Africa's sports talent network</span><h1>Where sports talent meets <em>opportunity.</em></h1><p>Build your sporting identity, share your best moments and get discovered by the people who can take your journey further.</p><div class="hero-buttons"><Link href="/register" class="public-button public-button-primary public-button-large">Join SportsUniverse <ArrowRight/></Link><a href="#athletes" class="public-button public-button-ghost public-button-large">Explore athletes</a></div><a v-if="highlights.length" href="#highlights" class="hero-watch"><CirclePlay/><span><strong>Watch the talent rising now</strong><small>Real highlights from the community</small></span></a></div>
                    <div class="hero-visual reveal visible" aria-label="Featured SportsUniverse athletes">
                        <div class="hero-frame hero-frame-main"><template v-if="highlights[0]"><img v-if="highlights[0].cover" :src="highlights[0].cover" :alt="`${highlights[0].athlete.name} highlight`"/><video v-else-if="highlights[0].video" :src="highlights[0].video" muted autoplay loop playsinline preload="metadata"/></template><div v-else class="hero-placeholder"><Trophy/><span>Your moment starts here</span></div><div class="hero-frame-shade"/><div v-if="highlights[0]" class="hero-athlete-label"><span class="live-dot"/><div><small>FEATURED TALENT</small><strong>{{ highlights[0].athlete.name }}</strong><span>{{ highlights[0].sport }} · {{ highlights[0].athlete.position }}</span></div></div></div>
                        <div v-if="highlights[1]" class="hero-frame hero-frame-small"><img v-if="highlights[1].cover" :src="highlights[1].cover" :alt="`${highlights[1].athlete.name} highlight`"/><video v-else :src="highlights[1].video" muted playsinline preload="metadata"/><span><CirclePlay/> {{ highlights[1].sport }}</span></div>
                        <div class="hero-proof"><div class="proof-icons"><span v-for="athlete in athletes.slice(0,3)" :key="athlete.slug"><img v-if="athlete.image" :src="athlete.image" alt=""/><span v-else>{{ athlete.name.slice(0,1) }}</span></span></div><strong>Talent lives here</strong><small>Join the sporting community</small></div>
                    </div>
                </div>
                <div class="hero-marquee"><span>SHOWCASE</span><i/> <span>DISCOVER</span><i/> <span>CONNECT</span><i/> <span>OPPORTUNITY</span><i/> <span>SPORTSUNIVERSE</span></div>
            </section>

            <section v-if="highlights.length" id="highlights" class="public-section highlights-section reveal"><div class="public-container"><header class="public-section-head"><div><span class="public-kicker"><CirclePlay/> Must watch</span><h2>Top athlete highlights</h2><p>Big moments. Raw talent. The next generation showing what they can do.</p></div><Link href="/feed" class="public-text-link">See all highlights <ArrowRight/></Link></header><div class="highlight-rail"><HighlightCard v-for="(item,index) in highlights.slice(0,6)" :key="item.id" :item="item" :large="index===0"/></div></div></section>

            <section v-if="highlights.length" class="public-section trending-section reveal"><div class="public-container"><header class="public-section-head compact"><div><span class="public-kicker"><Sparkles/> Right now</span><h2>Trending on SportsUniverse</h2></div></header><div class="filter-row" role="group" aria-label="Filter highlights by sport"><button v-for="sport in filterSports" :key="sport" type="button" :class="{ active: activeSport === sport }" @click="activeSport=sport">{{ sport }}</button></div><div class="trending-grid"><HighlightCard v-for="item in filteredHighlights.slice(0,4)" :key="item.id" :item="item"/></div></div></section>

            <section v-if="athletes.length" id="athletes" class="public-section athletes-section reveal"><div class="public-container"><header class="public-section-head"><div><span class="public-kicker"><Award/> Ones to know</span><h2>Athletes to watch</h2><p>Discover driven athletes building their sporting story.</p></div><Link href="/login" class="public-text-link">Discover more <ArrowRight/></Link></header><div class="athlete-rail"><AthleteCard v-for="athlete in athletes" :key="athlete.slug" :athlete="athlete"/></div></div></section>

            <section class="public-section how-section reveal"><div class="public-container"><div class="centered-heading"><span class="public-kicker">Your journey</span><h2>Four steps. One sporting future.</h2></div><div class="steps-grid"><article><span>01</span><UserRoundPlus/><h3>Create your sports profile</h3><p>Build a digital identity that tells your sporting story.</p></article><article><span>02</span><Upload/><h3>Showcase your talent</h3><p>Share highlights, achievements and performance statistics.</p></article><article><span>03</span><Search/><h3>Get discovered</h3><p>Be seen by scouts, clubs, coaches and the sporting world.</p></article><article><span>04</span><Trophy/><h3>Unlock opportunities</h3><p>Connect with trials, teams, academies and scholarships.</p></article></div></div></section>

            <section v-if="sports.length" id="sports" class="public-section sports-section reveal"><div class="public-container"><header class="public-section-head"><div><span class="public-kicker"><Compass/> Find your game</span><h2>Explore by sport</h2></div></header><div class="sports-grid"><a v-for="(sport,index) in sports" :key="sport.slug" :href="`/feed/sport/${encodeURIComponent(sport.name)}`" :style="{ '--sport-accent': sportArt[index % sportArt.length] }"><span class="sport-number">0{{ index+1 }}</span><div class="sport-ball"/><div><h3>{{ sport.name }}</h3><p v-if="sport.athletes">{{ format(sport.athletes) }} athletes</p><p v-else>Explore talent</p></div><ChevronRight/></a></div></div></section>

            <section v-if="opportunities.length" id="opportunities" class="public-section opportunities-section reveal"><div class="public-container"><header class="public-section-head"><div><span class="public-kicker"><BriefcaseBusiness/> Make your move</span><h2>Find your next opportunity</h2><p>Trials, scholarships, teams and development programmes—one connection away.</p></div><Link href="/login" class="public-text-link">View opportunities <ArrowRight/></Link></header><div class="opportunity-grid"><article v-for="opportunity in opportunities" :key="opportunity.id"><div class="opportunity-top"><span>{{ opportunity.type.replaceAll('_',' ') }}</span><BriefcaseBusiness/></div><h3>{{ opportunity.title }}</h3><p><MapPin/>{{ opportunity.location || 'Location to be confirmed' }}</p><small>{{ opportunity.host }}</small><div><span v-if="opportunity.deadline">Closes {{ new Date(opportunity.deadline).toLocaleDateString('en-ZA',{day:'numeric',month:'short'}) }}</span><Link href="/login">View <ArrowRight/></Link></div></article></div></div></section>

            <section class="scout-section reveal"><div class="public-container scout-grid"><div><span class="public-kicker"><ShieldCheck/> For scouts, clubs & coaches</span><h2>Discover tomorrow's champions today.</h2><p>Search athlete profiles, review authentic highlights and connect with emerging sporting talent across South Africa.</p><div><Link href="/login" class="public-button public-button-light">Discover talent <ArrowRight/></Link><Link href="/register" class="public-button public-button-outline">Join as a scout or club</Link></div></div><div class="scout-search-card"><div class="mock-search"><Search/> Search by sport, position or location</div><div v-for="athlete in athletes.slice(0,3)" :key="athlete.slug" class="scout-result"><span class="public-avatar"><img v-if="athlete.image" :src="athlete.image" alt=""/><span v-else>{{ athlete.name.slice(0,2) }}</span></span><div><strong>{{ athlete.name }}</strong><small>{{ athlete.sport }} · {{ athlete.position || 'Athlete' }}</small></div><span>{{ athlete.location }}</span><ChevronRight/></div><div v-if="!athletes.length" class="scout-empty"><UsersRound/><strong>Your next signing is on SportsUniverse</strong></div></div></div></section>

            <section v-if="Object.values(stats).some(Boolean)" class="public-stats reveal"><div class="public-container stats-grid"><div v-if="stats.athletes"><strong>{{ format(stats.athletes) }}+</strong><span>Athletes</span></div><div v-if="stats.highlights"><strong>{{ format(stats.highlights) }}+</strong><span>Published highlights</span></div><div v-if="stats.sports"><strong>{{ format(stats.sports) }}</strong><span>Sports represented</span></div><div v-if="stats.opportunities"><strong>{{ format(stats.opportunities) }}</strong><span>Open opportunities</span></div></div></section>

            <section class="community-section reveal"><div class="public-container community-grid"><div class="community-cards"><div class="community-post post-one"><span class="public-avatar">SU</span><div><strong>Built for your sporting journey</strong><small>Profiles · Highlights · Connections</small></div><Sparkles/></div><div class="community-post post-two"><Trophy/><div><small>ACHIEVEMENT UNLOCKED</small><strong>Personal best shared with the world.</strong></div></div><div class="community-post post-three"><UsersRound/><div><strong>A community behind every athlete</strong><small>Follow. Support. Discover.</small></div></div></div><div><span class="public-kicker"><UsersRound/> More than a profile</span><h2>Your sporting community, all in one place.</h2><p>Share the work, celebrate the wins and connect with people who understand the journey. Once you join, your sporting world gets bigger.</p><Link href="/register" class="public-text-link">Join the community <ArrowRight/></Link></div></div></section>

            <section class="final-cta reveal"><div class="final-cta-glow"/><div class="public-container"><span class="public-kicker">This is your moment</span><h2>Your talent deserves<br/>to be seen.</h2><p>Build your profile. Share your journey. Connect with the sporting world.</p><div><Link href="/register" class="public-button public-button-primary public-button-large">Create your free profile <ArrowRight/></Link><Link href="/feed" class="public-button public-button-ghost public-button-large">Explore SportsUniverse</Link></div></div></section>
        </main>
        <PublicFooter/>
    </div>
</template>
