<script setup lang="ts">
import { Head } from '@inertiajs/vue3';
import { Activity, Gauge, RefreshCw, TriangleAlert } from '@lucide/vue';
import { computed, onMounted, ref } from 'vue';
import AppShell from '../../Layouts/AppShell.vue';

const rows=ref<any[]>([]),loading=ref(true),error=ref(''),hours=ref(24),samples=ref(0);
const slow=computed(()=>rows.value.filter(row=>row.p95_ms>=1000).length);
const load=async()=>{loading.value=true;error.value='';try{const response=await fetch(`/api/v1/admin/page-performance?hours=${hours.value}`,{credentials:'same-origin',headers:{Accept:'application/json'}}),payload=await response.json();if(!response.ok)throw new Error(payload.message??'Unable to load performance data.');rows.value=payload.data??[];samples.value=payload.meta?.samples??0}catch(e:any){error.value=e.message}finally{loading.value=false}};
const seconds=(ms:number)=>ms>=1000?`${(ms/1000).toFixed(2)}s`:`${ms}ms`;
onMounted(load);
</script>

<template><Head title="Page performance"/><AppShell><main class="performance-admin"><header><div><span><Gauge/> PLATFORM PERFORMANCE</span><h1>Page loading times</h1><p>Real browser navigation and Laravel response measurements from production.</p></div><div><select v-model="hours" @change="load"><option :value="24">Last 24 hours</option><option :value="72">Last 3 days</option><option :value="168">Last 7 days</option></select><button :disabled="loading" @click="load"><RefreshCw :class="{spin:loading}"/>Refresh</button></div></header><section class="performance-stats"><article><Activity/><small>RECORDED SAMPLES</small><strong>{{samples.toLocaleString()}}</strong></article><article><TriangleAlert/><small>SLOW PAGE GROUPS</small><strong>{{slow}}</strong></article></section><p v-if="error" class="performance-error">{{error}}</p><section class="performance-table"><header><span>Page</span><span>Source</span><span>Samples</span><span>Average</span><span>P95</span><span>Maximum</span></header><p v-if="loading">Loading performance measurements…</p><p v-else-if="!rows.length">No measurements have been recorded yet.</p><article v-for="row in rows" :key="`${row.kind}:${row.path}`" :class="{slow:row.p95_ms>=1000}"><strong>{{row.path}}</strong><span>{{row.kind}}</span><span>{{row.samples}}</span><span>{{seconds(row.average_ms)}}</span><span>{{seconds(row.p95_ms)}}</span><span>{{seconds(row.maximum_ms)}}</span></article></section></main></AppShell></template>

<style scoped>
.performance-admin{width:min(1180px,100%);margin:auto;padding:2rem 2rem 6rem}.performance-admin>header{display:flex;align-items:flex-end;justify-content:space-between;gap:2rem;padding:1.7rem;border-radius:22px;color:#fff;background:linear-gradient(135deg,#111d31,#34528b)}.performance-admin header span{display:flex;gap:.4rem;align-items:center;font-size:.6rem;font-weight:900;letter-spacing:.1em}.performance-admin h1{margin:.5rem 0 .2rem;font-size:2rem}.performance-admin header p{margin:0;color:#dbe5f5}.performance-admin header>div:last-child{display:flex;gap:.5rem}.performance-admin select,.performance-admin button{padding:.65rem .8rem;border:0;border-radius:10px;background:#fff}.performance-admin button{display:flex;gap:.35rem;align-items:center;font-weight:800}.performance-admin button svg{width:15px}.performance-stats{display:grid;grid-template-columns:repeat(2,1fr);gap:.8rem;margin:1rem 0}.performance-stats article{display:grid;grid-template-columns:42px 1fr;align-items:center;padding:1rem;border:1px solid #e0e6ef;border-radius:15px;background:#fff}.performance-stats article>svg{grid-row:1/3;width:22px;color:#476fea}.performance-stats small{font-size:.5rem}.performance-stats strong{font-size:1.3rem}.performance-table{overflow:hidden;border:1px solid #e0e6ef;border-radius:15px;background:#fff}.performance-table>header,.performance-table>article{display:grid;grid-template-columns:minmax(240px,2fr) repeat(5,minmax(70px,.6fr));gap:.5rem;align-items:center;padding:.8rem 1rem}.performance-table>header{color:#778396;background:#f3f6fa;font-size:.55rem;font-weight:850}.performance-table>article{border-top:1px solid #edf0f4;font-size:.62rem}.performance-table>article.slow{background:#fff7f0}.performance-table>p{padding:2rem;text-align:center}.performance-error{padding:.8rem;color:#a32d50;background:#fff0f4}@media(max-width:700px){.performance-admin{padding:1rem .8rem 6rem}.performance-admin>header{align-items:stretch;flex-direction:column}.performance-table{overflow:auto}.performance-table>header,.performance-table>article{min-width:720px}}
</style>
