import { useState } from 'react';
import { ActivityIndicator, Alert, FlatList, Image, KeyboardAvoidingView, Modal, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import * as WebBrowser from 'expo-web-browser';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '../../../src/api/client';
import { PrimaryButton } from '../../../src/components/PrimaryButton';
import { ScreenMessage } from '../../../src/components/ScreenMessage';
import { colors, radius, spacing } from '../../../src/theme';
import type { OpportunityApplication, PaginatedResponse } from '../../../src/types/api';
import { absoluteMediaUrl } from '../../../src/utils/url';

const decisions = ['reviewing', 'shortlisted', 'accepted', 'rejected'] as const;

export default function ApplicantsScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const client = useQueryClient();
  const [selected, setSelected] = useState<OpportunityApplication | null>(null);
  const [status, setStatus] = useState<(typeof decisions)[number]>('reviewing');
  const [notes, setNotes] = useState('');
  const applications = useQuery({ queryKey: ['opportunity-applicants', id], enabled: Boolean(id), queryFn: async () => (await api.get<PaginatedResponse<OpportunityApplication>>(`/opportunities/${id}/applications`, { params: { per_page: 50 } })).data.data });
  const review = useMutation({
    mutationFn: () => api.patch('/applications/' + selected!.id, { status, reviewer_notes: notes.trim() || null }),
    onSuccess: () => { setSelected(null); client.invalidateQueries({ queryKey: ['opportunity-applicants', id] }); client.invalidateQueries({ queryKey: ['club-pipeline'] }); client.invalidateQueries({ queryKey: ['opportunities', 'mine'] }); },
    onError: error => Alert.alert('Application not updated', message(error)),
  });
  const openReview = (item: OpportunityApplication) => { setSelected(item); setStatus(item.status === 'submitted' || item.status === 'withdrawn' ? 'reviewing' : item.status as any); setNotes(item.reviewer_notes || ''); };
  const items = applications.data ?? [];
  return <SafeAreaView edges={['top']} style={styles.safe}><View style={styles.header}><Pressable accessibilityLabel="Go back" onPress={() => router.back()}><Ionicons name="chevron-back" size={26} color="#fff" /></Pressable><Text style={styles.headerTitle}>Applicants</Text><Text style={styles.count}>{items.length}</Text></View><FlatList data={items} keyExtractor={item => item.id} contentContainerStyle={items.length ? styles.list : styles.empty} refreshing={applications.isRefetching} onRefresh={() => applications.refetch()} ItemSeparatorComponent={() => <View style={{ height: 10 }} />} renderItem={({ item }) => <ApplicantCard item={item} onReview={() => openReview(item)} />} ListEmptyComponent={applications.isLoading ? <ActivityIndicator style={{ marginTop: 100 }} color={colors.blue} /> : applications.isError ? <ScreenMessage icon="cloud-offline-outline" title="Applicants unavailable" message={message(applications.error)} /> : <ScreenMessage icon="people-outline" title="No applicants yet" message="Applications will appear here as athletes apply." />} /><ReviewModal item={selected} status={status} setStatus={setStatus} notes={notes} setNotes={setNotes} busy={review.isPending} onClose={() => setSelected(null)} onSave={() => review.mutate()} /></SafeAreaView>;
}

function ApplicantCard({ item, onReview }: { item: OpportunityApplication; onReview: () => void }) {
  const photo = absoluteMediaUrl(item.applicant.image);
  const initial = item.applicant.name[0]?.toUpperCase();
  return <View style={styles.card}><Pressable onPress={() => item.applicant.slug && router.push(`/profile/${item.applicant.slug}` as never)} style={styles.identity}>{photo ? <Image source={{ uri: photo }} style={styles.avatar} /> : <View style={[styles.avatar, styles.fallback]}><Text style={styles.initial}>{initial}</Text></View>}<View style={styles.copy}><Text style={styles.name}>{item.applicant.name}</Text><Text style={styles.applied}>Applied {new Date(item.created_at).toLocaleDateString()}</Text></View><Status value={item.status} /></Pressable>{item.cover_letter ? <View style={styles.cover}><Text style={styles.label}>Cover letter</Text><Text style={styles.coverText}>{item.cover_letter}</Text></View> : null}<View style={styles.documents}>{item.resume ? <DocumentButton label="CV / Resume" mediaId={item.resume.id} /> : null}{item.documents?.map(document => <DocumentButton key={document.id} label={document.name} mediaId={document.id} />)}{!item.resume && !item.documents?.length ? <Text style={styles.noDocs}>No documents attached.</Text> : null}</View>{item.reviewer_notes ? <View style={styles.notes}><Text style={styles.label}>Reviewer notes</Text><Text style={styles.noteText}>{item.reviewer_notes}</Text></View> : null}<View style={styles.actions}><Pressable onPress={() => item.applicant.slug && router.push(`/profile/${item.applicant.slug}` as never)} style={styles.secondary}><Ionicons name="person-outline" size={16} color="#fff" /><Text style={styles.buttonText}>Profile</Text></Pressable><Pressable onPress={onReview} style={styles.primary}><Ionicons name="clipboard-outline" size={16} color="#fff" /><Text style={styles.buttonText}>Review</Text></Pressable></View></View>;
}

function DocumentButton({ label, mediaId }: { label: string; mediaId: string }) {
  const [busy, setBusy] = useState(false);
  const open = async () => { setBusy(true); try { const response = await api.post<{ data: { url: string } }>(`/media/${mediaId}/temporary-link`); await WebBrowser.openBrowserAsync(response.data.data.url); } catch (error) { Alert.alert('Document unavailable', message(error)); } finally { setBusy(false); } };
  return <Pressable disabled={busy} onPress={open} style={styles.document}><Ionicons name="document-text-outline" size={17} color="#79A3FF" /><Text numberOfLines={1} style={styles.documentText}>{label}</Text>{busy ? <ActivityIndicator size="small" color={colors.blue} /> : <Ionicons name="open-outline" size={15} color={colors.muted} />}</Pressable>;
}
function Status({ value }: { value: string }) { return <View style={[styles.status, value === 'accepted' && styles.accepted, value === 'rejected' && styles.rejected, value === 'shortlisted' && styles.shortlisted]}><Text style={styles.statusText}>{value}</Text></View>; }
function ReviewModal({ item, status, setStatus, notes, setNotes, busy, onClose, onSave }: { item: OpportunityApplication | null; status: (typeof decisions)[number]; setStatus: (value: (typeof decisions)[number]) => void; notes: string; setNotes: (value: string) => void; busy: boolean; onClose: () => void; onSave: () => void }) {
  return <Modal visible={Boolean(item)} transparent animationType="slide" onRequestClose={onClose}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.overlay}><Pressable style={StyleSheet.absoluteFill} onPress={onClose} /><View style={styles.sheet}><View style={styles.sheetHeader}><View><Text style={styles.sheetTitle}>Review application</Text><Text style={styles.sheetName}>{item?.applicant.name}</Text></View><Pressable onPress={onClose}><Ionicons name="close" size={24} color={colors.muted} /></Pressable></View><Text style={styles.label}>Decision</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.decisions}>{decisions.map(value => <Pressable key={value} onPress={() => setStatus(value)} style={[styles.decision, status === value && styles.decisionActive]}><Text style={[styles.decisionText, status === value && styles.decisionTextActive]}>{value}</Text></Pressable>)}</ScrollView><Text style={styles.label}>Private reviewer notes</Text><TextInput value={notes} onChangeText={setNotes} multiline maxLength={5000} placeholder="Assessment, next steps or reasons for this decision…" placeholderTextColor={colors.muted} style={styles.input} /><PrimaryButton label="Update application" loading={busy} onPress={onSave} style={{ marginTop: 16 }} /></View></KeyboardAvoidingView></Modal>;
}
function message(error: any) { return error?.response?.data?.message || Object.values(error?.response?.data?.errors || {}).flat()[0] as string || 'Please try again.'; }

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.navy }, header: { height: 56, paddingHorizontal: spacing.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.line }, headerTitle: { color: '#fff', fontSize: 17, fontWeight: '900' }, count: { minWidth: 26, color: '#79A3FF', textAlign: 'right', fontWeight: '900' }, list: { padding: spacing.md, paddingBottom: 40 }, empty: { flexGrow: 1 }, card: { padding: spacing.md, borderWidth: 1, borderColor: colors.line, borderRadius: radius.lg, backgroundColor: colors.surface }, identity: { flexDirection: 'row', alignItems: 'center', gap: 11 }, avatar: { width: 52, height: 52, borderRadius: 26 }, fallback: { alignItems: 'center', justifyContent: 'center', backgroundColor: colors.blue }, initial: { color: '#fff', fontSize: 17, fontWeight: '900' }, copy: { flex: 1 }, name: { color: '#fff', fontSize: 15, fontWeight: '900' }, applied: { color: colors.muted, fontSize: 9, marginTop: 4 }, status: { paddingHorizontal: 8, paddingVertical: 5, borderRadius: radius.pill, backgroundColor: colors.blue }, accepted: { backgroundColor: colors.green }, rejected: { backgroundColor: colors.danger }, shortlisted: { backgroundColor: colors.orange }, statusText: { color: '#fff', fontSize: 8, fontWeight: '900', textTransform: 'uppercase' }, cover: { marginTop: 15, padding: 12, borderRadius: radius.md, backgroundColor: colors.navyLight }, label: { color: '#DCE7F5', fontSize: 10, fontWeight: '900', textTransform: 'uppercase', letterSpacing: .4, marginBottom: 7 }, coverText: { color: '#D8E2EE', fontSize: 11, lineHeight: 17 }, documents: { gap: 7, marginTop: 12 }, document: { minHeight: 42, paddingHorizontal: 11, flexDirection: 'row', alignItems: 'center', gap: 8, borderRadius: 10, backgroundColor: colors.surfaceRaised }, documentText: { flex: 1, color: '#DCE7F5', fontSize: 10, fontWeight: '800' }, noDocs: { color: colors.muted, fontSize: 10 }, notes: { marginTop: 13, padding: 11, borderLeftWidth: 3, borderLeftColor: colors.blue, backgroundColor: colors.navyLight }, noteText: { color: colors.muted, fontSize: 10, lineHeight: 15 }, actions: { flexDirection: 'row', gap: 8, marginTop: 15 }, secondary: { flex: 1, minHeight: 40, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, borderRadius: 10, backgroundColor: colors.surfaceRaised }, primary: { flex: 1, minHeight: 40, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, borderRadius: 10, backgroundColor: colors.blue }, buttonText: { color: '#fff', fontSize: 10, fontWeight: '900' },
  overlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,.66)' }, sheet: { padding: spacing.lg, paddingBottom: 35, borderTopLeftRadius: radius.lg, borderTopRightRadius: radius.lg, backgroundColor: colors.navyLight }, sheetHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 18 }, sheetTitle: { color: '#fff', fontSize: 20, fontWeight: '900' }, sheetName: { color: '#79A3FF', fontSize: 11, marginTop: 4 }, decisions: { gap: 7, paddingBottom: 16 }, decision: { paddingHorizontal: 12, paddingVertical: 9, borderWidth: 1, borderColor: colors.line, borderRadius: radius.pill }, decisionActive: { borderColor: colors.blue, backgroundColor: colors.blue }, decisionText: { color: colors.muted, fontSize: 10, fontWeight: '800', textTransform: 'capitalize' }, decisionTextActive: { color: '#fff' }, input: { height: 130, padding: 13, color: '#fff', textAlignVertical: 'top', borderWidth: 1, borderColor: colors.line, borderRadius: radius.md, backgroundColor: colors.surface },
});
