import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '../../../src/api/client';
import { PrimaryButton } from '../../../src/components/PrimaryButton';
import { colors, radius, spacing } from '../../../src/theme';
import type { Video } from '../../../src/types/api';

type Visibility = 'public' | 'followers' | 'private';
export default function EditPostScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const queryClient = useQueryClient();
  const post = useQuery({ queryKey: ['video', id], queryFn: async () => (await api.get('/videos/' + id)).data.data as Video, enabled: Boolean(id) });
  const [form, setForm] = useState({ caption: '', location_name: '', visibility: 'public' as Visibility, comments_enabled: true });
  useEffect(() => { if (post.data) setForm({ caption: post.data.caption ?? '', location_name: post.data.location?.name ?? '', visibility: post.data.visibility ?? 'public', comments_enabled: post.data.comments_enabled ?? true }); }, [post.data]);
  const save = useMutation({ mutationFn: async () => (await api.patch('/videos/' + id, { ...form, hashtags: [...form.caption.matchAll(/#([\p{L}\p{N}_]+)/gu)].map(match => match[1]) })).data.data as Video, onSuccess: async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ['videos', 'mine'] }), queryClient.invalidateQueries({ queryKey: ['feed'] }), queryClient.invalidateQueries({ queryKey: ['video', id] })]); Alert.alert('Post updated', 'Your changes have been saved.', [{ text: 'Done', onPress: () => router.back() }]); }, onError: (error: any) => Alert.alert('Post not updated', Object.values(error?.response?.data?.errors || {}).flat()?.[0] as string || error?.response?.data?.message || 'Please try again.') });

  return <SafeAreaView edges={['top']} style={styles.safe}><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={styles.header}><Pressable accessibilityLabel="Go back" hitSlop={12} onPress={() => router.back()}><Ionicons name="chevron-back" size={26} color="#fff" /></Pressable><Text style={styles.headerTitle}>Edit post</Text><View style={{ width: 26 }} /></View>{post.isLoading ? <ActivityIndicator style={styles.flex} color={colors.blue} /> : <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.label}>Caption</Text><TextInput value={form.caption} onChangeText={caption => setForm(current => ({ ...current, caption }))} multiline maxLength={2200} placeholder="Tell the story…" placeholderTextColor="#71849B" style={[styles.input, styles.caption]} textAlignVertical="top" /><Text style={styles.counter}>{form.caption.length}/2200</Text><Text style={styles.label}>Location</Text><TextInput value={form.location_name} onChangeText={location_name => setForm(current => ({ ...current, location_name }))} maxLength={160} placeholder="Stadium, city or training ground" placeholderTextColor="#71849B" style={styles.input} /><Text style={styles.label}>Visibility</Text><View style={styles.visibility}>{(['public', 'followers', 'private'] as Visibility[]).map(value => <Pressable key={value} onPress={() => setForm(current => ({ ...current, visibility: value }))} style={[styles.visibilityButton, form.visibility === value && styles.visibilityActive]}><Ionicons name={value === 'public' ? 'globe-outline' : value === 'followers' ? 'people-outline' : 'lock-closed-outline'} size={18} color={form.visibility === value ? '#fff' : colors.muted} /><Text style={[styles.visibilityText, form.visibility === value && { color: '#fff' }]}>{value}</Text></Pressable>)}</View><View style={styles.toggle}><View style={styles.toggleCopy}><Text style={styles.toggleTitle}>Allow comments</Text><Text style={styles.toggleDescription}>Members can respond to this post.</Text></View><Switch value={form.comments_enabled} onValueChange={comments_enabled => setForm(current => ({ ...current, comments_enabled }))} trackColor={{ false: colors.surfaceRaised, true: colors.blue }} /></View><PrimaryButton label="Save changes" loading={save.isPending} onPress={() => save.mutate()} style={{ marginTop: 25 }} /></ScrollView>}</KeyboardAvoidingView></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.navy }, flex: { flex: 1 }, header: { height: 56, paddingHorizontal: spacing.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.line }, headerTitle: { color: '#fff', fontSize: 18, fontWeight: '900' }, content: { padding: spacing.lg, paddingBottom: 45 }, label: { color: '#DCE7F5', fontSize: 12, fontWeight: '800', marginBottom: 7, marginTop: 18 }, input: { minHeight: 50, paddingHorizontal: 15, borderRadius: radius.md, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface, color: '#fff' }, caption: { height: 150, paddingTop: 14 }, counter: { color: colors.muted, fontSize: 10, textAlign: 'right', marginTop: 5 }, visibility: { flexDirection: 'row', gap: 7 }, visibilityButton: { flex: 1, minHeight: 62, alignItems: 'center', justifyContent: 'center', gap: 5, borderRadius: radius.md, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface }, visibilityActive: { borderColor: colors.blue, backgroundColor: colors.blue }, visibilityText: { color: colors.muted, fontSize: 10, fontWeight: '800', textTransform: 'capitalize' }, toggle: { marginTop: 24, padding: spacing.md, flexDirection: 'row', alignItems: 'center', borderRadius: radius.md, backgroundColor: colors.surface }, toggleCopy: { flex: 1 }, toggleTitle: { color: '#fff', fontSize: 13, fontWeight: '900' }, toggleDescription: { color: colors.muted, fontSize: 10, marginTop: 3 } });
